apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: intel-gpu-plugin
    namespace: intel-gpu-plugin
spec:
    interval: 5m
    chart:
        spec:

            chart: intel-gpu-plugin
            version: 0.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values: