apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: intel-device-plugins-gpu
    namespace: intel-device-plugins-gpu
spec:
    interval: 5m
    chart:
        spec:

            chart: intel-device-plugins-gpu
            version: 0.31.1
            sourceRef:
                kind: HelmRepository
                name: intel
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3