apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:6NKi/wIiWc4Dsy7MFCiloOX10UMmUHRbWfn8iJVuG9MTIIns+X05wuzc8DTsFTJVtYpwUgRm6rtYv/Y8HbYPa1o=,iv:ZFdj1kyiDkGTTKMWxCIb+A/4DsAGL0/rOjnHv+dwwGQ=,tag:Q8FOxWqmroHcqyoJOSc6dQ==,type:comment]
    #ENC[AES256_GCM,data:Ypu/pEWfZDNbtxZ141iJpYxG+yu900qnoP6R//Oq3qEg4xNf+ovC4amhdPQ=,iv:WH0IafJJ+BtD/oL3pcMxSnH6w2wmESxLMJzPDJkfLho=,tag:oNkedca6GVnw/GAWQRUzxg==,type:comment]
    VIP: ENC[AES256_GCM,data:Mt1ZbgKR5ST0siGtCg==,iv:zf1ooGYlEJFD79wVtlKhM/H24FCnpErC1SQ+7q1gozA=,tag:yZKxx7aO7w686iHPGkZ0AA==,type:str]
    #ENC[AES256_GCM,data:PeSQRF8Dfs3cYQS5T/pyeNJ4U+2PiCXab2rD,iv:/Gbsr0q0GONTM4S1vi7gNBJivmoC7BXz6mvhT/8PV5Y=,tag:B/OTjkLwFDXbDtDLL8hY4Q==,type:comment]
    #ENC[AES256_GCM,data:nSTVgUDXkmRN/TNo6Ajih1lqOWZAclJg9UanREJSlypTIMaM8fYY4xPY0KkYt/NLHo9IXK2qHDj4ELu8MJ55pNaZJXtHRB/bmRh+2OXmD/E4CXMU7tB8/W4=,iv:PI+CyFcOnTUUV5Iyr7Gwmk5yqiy+kjrVOcxm9lLzy30=,tag:EWI9SESdVBmCG1oOcKozIg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:XBZkpGmbzA+YRz/ynOg=,iv:k8b8z9w1vysEKHskOBo6ooD5F5D/H7LjJ7wOZjnQD+4=,tag:ho6asEGcc3reh5OEy5zD8w==,type:str]
    #ENC[AES256_GCM,data:sZ6VjElfjJ4ex7s6VXa+bDnmuwtdX0xdInNCJLpvls0haA==,iv:3HJjI3lixLxUWBPfUiD1vENx/ChvvellcZzaJVDgzig=,tag:DzHfjrMq1H+u1vURjyjakg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:PF6hmuYrhtXleXiCFA==,iv:i1UU6dZtTgCw8s2K9wUQArolV6f1cHlbAA4Z9vC3rG4=,tag:qn7tPds31GyWIrAqOUmcnQ==,type:str]
    #ENC[AES256_GCM,data:zwlkoblXmBTUpjFfI5d/8mA8wTWxA9ESOF1r/RMtom2MdUFiXNmp8rwGBs6877g=,iv:msD5xs0Kpx/W/+tIpUrXHzKZjjSKCH7zrwkek53SJs8=,tag:ND4RY5qt2Vba//F5OF103A==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:BRwTBkJNG6NcHNgBafKY3dMhH8cn/3u0ovqsWJhdeQ==,iv:10MGJSBYoL7bNexy3L4ILuTCAGVhlpTMqnWKFUX1CoA=,tag:sYFZ/oRxdnTLmLySNru7wQ==,type:str]
    #ENC[AES256_GCM,data:LdAGvDMnyGkwtACpoeVs5Xa4jMhBBhSXHAoQd6MuTJsrQyJ63RGy0db3b/XIS12Gldtbf59oIooTwLenQlMwOHIJzb9VwZQBDc/sItKUGPmTZw==,iv:XKjsdK4Kmetan4uxb7po+CXJOZs6tkRELxooBWX00fs=,tag:ko0xgihM6ExLn/KHmmmDvg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:Vk8Q48x1i29Ht2nViK+s,iv:QhpzFFxJY9ZAbxjo8HljLtgpC94DLVxa/R8X8JtzzQc=,tag:dZErG/divnmgVHJYkT9CUw==,type:str]
    #ENC[AES256_GCM,data:jZsAeTSUimmjdZOepsDaps0scC1W3+K8ou+6+DkcvfEw,iv:oK9H/81ShBfgJsXg3vvspfjXd7xfOmccTBPfZhp/KjA=,tag:wyo8e0MlxeCQjYdW1XOWyA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:/hWnmhNSQBaRlaUX/S+Q,iv:xv5xsM97kn2mkR3tW9anQsMIBldjSRs/ea3SFj5LVRg=,tag:duXo5JFSkYM9XOD7FLEAaA==,type:str]
    #ENC[AES256_GCM,data:1ZlzRkC8lYeWe+h4NjMt8v14X3tqOp+h1a5HvoRvWDUxPn5xe+MlVjuEYw/NYe3RzwE88DORyxIcZKh5UEnlkFHkrb6hWIFoS91GHi7rKvU=,iv:effrHN1IUd8ZoV1BtcP0bOFLWkG/JZVeo6D54P1ximw=,tag:8DyeQFDJTVK+gGKj18weXA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:9UhZAWDevd3wKIF2SKZO,iv:N7cLlLWjqI/5Qo7Vy/bZWwOL9YvHnQBELIsw05okxig=,tag:24DXUGHJGdZPBvpGEo3SOg==,type:str]
    #ENC[AES256_GCM,data:FeEr7fHpFknm5q3x4IQpbPRC5V+AlkAAIBwqmQfnKo21KZaHD16aclb2rTjanKPQXDLFTBuhM0TUIQNB909XD7GYJCggxL/1/D/XHeIdLVEo71t6GGfx,iv:vWU0UO/VJbuuY5tZj+TYFCfwYi9qOcPYecJiBGhhgL4=,tag:z6fgyGcP3b44tYqep6pUkw==,type:comment]
    #ENC[AES256_GCM,data:nll9JmsCD/pCJ93oFQrUV5tAzhBGg/9hB1q1V3bgFrtDf0Km1vNkS+RzrKNTjFpxym25AKhTjdT2bqr/GTph4dkFWdy2nboslP06GCsiedOe500p1K0dP5ggX6nqbUcUy1sQFyo01IWe1LI/tlbW+7gk8u5ide9lYPiPyg==,iv:KPPZ9kQOkolgAAroN0n5fZibZkujla/VWOX4jTf3LN8=,tag:pFJRtxIRoaiE4PGfD8qp+Q==,type:comment]
    #ENC[AES256_GCM,data:jiUrCCS2z8bPop0jS7U49M4o3hCq5rhetStUPFo3vPdSQmcmOKnzd/3bHiLiasTkcrL6RAyVHqo3zR+IVWwE6phHHatGucWMSDjGZ43+KpM=,iv:ALYQJs0p1BgmHvKMmaLyShpBIM/SmFmTqbmMGR/ZTpc=,tag:UQJ1gs73x2NQLon/4RXeeA==,type:comment]
    #ENC[AES256_GCM,data:vCXMiMIBeeDrjKv9oGyeaXdc6MVjIA1/vs6AxJlRF0N3YqeSDMzbfJxDHXd8TlBYO69UmgD5,iv:XdLkouGiBuaXt93UvSklOZjl1xVVvqdOW/waZ+aTU8I=,tag:h80kONQrJUsh0bVHSNVwCQ==,type:comment]
    DDNS_URL: ENC[AES256_GCM,data:PIoVMHYBgJNYKygsiV8=,iv:kTBPNcucujSOHFAWXUAUC8U5/Qr/A5w2QHSjrKE7bJc=,tag:Uual/6DfYDy0sSGr/+miwg==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:0hVeku7MDNZnYXjV,iv:PcqBO2fWO+g3S4tHpQH5wHFrdzE3xWdd0WjkIlY2Lug=,tag:/IhhWuCmD+rzXVj1aBlqoQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:8zJiPymwta33h4Fz4rOrOcI=,iv:GkSipvTYjJE0gEdlCsCim6KVBAf/ud8kjaMWYATKcM4=,tag:edG6NfeMgnbbk3xeCt+8KA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:pdkn/+G1C7cpO3op5QZ5ZiM9gD/+If7lSFBDbG/K/oEAgS1HSPEQ/Q==,iv:qeGgUATBl8WBmYfalVth+llOFDLL3wMw9FPwMytioTc=,tag:OzULvjNCPL243txdhLzNYQ==,type:str]
    #ENC[AES256_GCM,data:jp914XFOh+KlmQRXlEPyNE/s/GvwTJOtdnH4qgxSrTkNMLuDC3djmUnDRTEyyQ0HFKmkpveu8yE=,iv:Y+MRFNYzTo7NJujbKf3baALhj1ZH73Lx1+1B5oBTjcc=,tag:HFpJpGzU994a2Urn5QQngw==,type:comment]
    #ENC[AES256_GCM,data:aq6Dy591U3FePOZ60Y+XDOtgCk5Fb7kOtQ==,iv:Ii1r1mXmrvaux+rzvghSzWD9QWPeLYVfAy3DLj2snQo=,tag:xVHKm6/mDO0Nap2SZmbqLg==,type:comment]
    #ENC[AES256_GCM,data:X63oSUdiJasKd7wvrLZMK9Vz6RBnm9FAMDd67ZrgbPLtk73kxehO4qzCRJ4f+cfkcDVuDHOuUMSltnCts6W244zhHbLOSWQG5nFXgME=,iv:a0T6Crmu5Sd4Ec4PqX+2kd6H00D2vVrmEISbJjxkLzI=,tag:gb5NAUjKz2NHRGivxgb4Yw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:YTQT7QhaNT35X1b/mILdz4iWOZitYLMg8LAxE4QVkDKkSorKkFFzvXBNR2StefaP,iv:vooyn+zKYLrQIjt0mX3Z459exstipkZwq77JPsbOHWg=,tag:VmkQSaGcW8b5+rlPaw4QVw==,type:str]
    #ENC[AES256_GCM,data:69vpXOuBjLwQc0vz5TvSAnYXq+gDw5LXw/ocRYXzV1kJlA5KlboqbdGKghiF9zHPrOCiyvvntF8H3WiSzVZZ2QmuxD46H/g=,iv:jUoG67GZePaq6rfjKZOjo0O/8DLKzc+7hILinhRxuzo=,tag:prSUpI913MBiJizTvxGmWQ==,type:comment]
    #ENC[AES256_GCM,data:Cr4ZyhzlxtSIRr4BUgiTIFbUnFyeQT1GNkgTPROLZHSqbxmcTbmiMGx18tK0umF74VZO6o+j,iv:cdEJbXWEuCgmMaOYISKwD+08A/rxi7I2/3UyDKLV+O0=,tag:jbRFDVdLdjKQRvcWba4DZQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:mrGO29Y0+A==,iv:wmfOXcW+K8Fj6KZAH+wTCagoHAZHbbkebD/ZxGPLrdM=,tag:NC1UUtOA3gytwNM6qSR4Mg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:iJPdx95EYTW0v5oagmc+JWX0avw=,iv:GIbWCO/7VFTWyZaeVq5VYQkKzgAHe6buJMQjZW6nGmk=,tag:IiMwCNe+0HDhPxlFU8In5g==,type:str]
    #ENC[AES256_GCM,data:kB5QlHRckfZdAHSDuYY=,iv:m2kqV7JKoRjQwfjpua1tGHdUtu8E1HJDY4UQBX7obTo=,tag:LNCMycCOeOdqfp0AMsMOfQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:VLqfOm778sPnwe4zIQ==,iv:uwNgfY13Eopa/Cgl5H7LqjCcPjHPDPtpeLvXvkuYDP8=,tag:dWdSHmVKOQ8ur3OxQzUl3w==,type:str]
    SVCNET: ENC[AES256_GCM,data:TfvSqXlD4ibqQKVD9w==,iv:IlQYYo5u4rxIl632droWYmymE6nr3ez6MLmauwzTebQ=,tag:ZHtnOf/iuVeoH1Wo8Csn0w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:25mq3Q==,iv:eSHsamI+/iLSLjidDxRzzRCkwoV4MZBlcOPcS56QTGg=,tag:PjSp+gZpFUA+x9v4pVpTmA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MzV1bkYxL1BucmdLa2h2
            c2ZMTVg4RnNDTm8rNk1BZmNwVytZQUJ5UW5NCnYrdUxjQXpaTU1vOXExYUVpVDZz
            amVoT1RYOHlRRmJOODAvb3hQTzhaVGMKLS0tIHo3eFlXRGRCSmVSbkQrb1NmUW5M
            NEdPMlFMK1M2NzNIS21YSnZBbGUwVW8KbXvmX5MqebCs1PaxJx0xWRNF0Aqf0bNG
            wzchjfuvugZ6rG1IC2DudFxjRbT1GneV4ayxFASPyM2ogm+trAZeiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T15:08:00Z"
    mac: ENC[AES256_GCM,data:9H4gopzbgjVJ9mfdMN5YSjDHgzqAHU9S5pCwiCZc1kx0IFE/bjQ0H6IRb4iQVIFHBZ1Aml7DuaMtuPPan4nIeR5vK2RPt02VHXZd99mlbBbn7chBxukdk6rVEeh4LgZOkNcWHxpgQBa/rXGIW5wqUKIDcS9besbJ3X6UCTZkH8g=,iv:QR7frr7Plbxew61+v0OEIThlUkHuR3m1sLo6y9zJfwU=,tag:k2owbJjR9y5jWmwKnvItGg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
