apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:k2cKRGWSCh47zzFnabtNfJlqMidBK2xSwaXNAsf+2Apfqhg8biI+ZGcwUwBIFrQ8UoWm4ghRWXYMlqNjgk9sV2I=,iv:HxBORvsCt2ZIZI+36ozObWXMkQ2NOgUqLLIN0ZiSsME=,tag:iuxbQtrg8VZcTrHpDRvYxA==,type:comment]
    #ENC[AES256_GCM,data:uZWpcJRdQcwwf803TNPiwx2Bb6yJMTebDp97ti+0B3zq3tYpK1cd+OSETF8=,iv:PAgKbWQtJzTEMvIGOnRHywz2OJTzlyprM3yQ1hs2yD8=,tag:d0E3UwD9ZRg5ob2VafJPLA==,type:comment]
    VIP: ENC[AES256_GCM,data:VNaw0WW8Uyhs3onCdA==,iv:N3EWKEJHFvriiHLcjcU6j8DXsBgLP9c7kXPC+UHSMHk=,tag:If8FWPotnncbkeSUQUikzQ==,type:str]
    #ENC[AES256_GCM,data:UH9lUUdFpHDI1Jf+VOewxh3EcIfXm1BbOGt5,iv:mpjqiUjhtZP9k2WR1QO2Kyk8qMeJFnatvzWBsBIj4qc=,tag:yy9Zbjv84hJgTPx7PNvPdQ==,type:comment]
    #ENC[AES256_GCM,data:MyBY8QFB+bHejTFMQcM/sDjeg+t4wY6HWx7K21HdP4wcyPBo2oZ/unwzEj0Kc8eAdTaNP6mL6WrqJryg1fuQo7ySjJkskNGnxlEyvgLSZNUddC4jE1/cc2s=,iv:z4bHejRSN5dgtv72XitB0aHl1uRMX6DzwFrVnj+cPM0=,tag:8qgL2AnEF9VM0XBxLoPHCg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:T8SmtxBjDXLxEtxhb8U=,iv:XAcRTL9owlkjqzPHqBP0/7jR8nMUglDOIs0aLhYtkQM=,tag:Du97tOpnyoEpG8zR7Vm9+w==,type:str]
    #ENC[AES256_GCM,data:o79BmCSemBUwk3yw0LaoAKiX6Y3ejGnMr9d11O8lljODoQ==,iv:FwwVEqaI7Gtq2VWQPmD4VIltfQrmnEJgyykOYYQTs+Q=,tag:wztaR4KAGRV4UO+uSuOhKA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:Ish4pbdq6my0VNHT8A==,iv:wRS8Q9c7oMaXIloHWTF0a/MAbUChw4q4vJ2Fc8irE5c=,tag:BSDxHi4A77urjl3zaNd/WQ==,type:str]
    #ENC[AES256_GCM,data:p0CHsW5u6toIhZuLJSymntrs1qtgfteBYhQ0/X9byjt/wyzuu4O1YrGY/vZXzkc=,iv:OfmQ6XQ4SSxltxxZUyMGuzsiuGcrcI6WQbt2FM2rmfc=,tag:D5nEZZjpCKA5Q6KIl5bAIA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:fLOSR7x4ZC1ObZS5pVccsSu8oxXWXhaakqCCsho62A==,iv:AYu2HQTnUVfDKfxx1rGQnkPPkaRm1WpwMaZBC1SXAFI=,tag:r50Eze+ddsjLuGk/V3k3yw==,type:str]
    #ENC[AES256_GCM,data:mTuPb0Fq5PoeaXEHrtSO31MTQT9BLlKe9zNCQoLmO2WRu48BF2yb5pqLwFb2A7dRdy67IzkHoz63aib8LivrU1/irLEoNHuGBCpQ695sJOAZsA==,iv:GhuGxgSl8mLG/sW618+2SJPm8SJMnlYBk9Uo9vgAycQ=,tag:/8hCKrOmb/f/qOe/NBs9kw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:l1BLY00LVzVfRuSPRjsg,iv:q48Iv5LXqIwGz27ZDGos64NCfV+cUVJx4wp6KLdixno=,tag:i6zBcLjie5qSIvEYZW2MUw==,type:str]
    #ENC[AES256_GCM,data:+0Qn2zehCZ6YZK2EHrVMpP7DNEmopwYzL/miSm3namc5,iv:j5LvEvaEjsGmacCwu1s5wu6+ufReMbga7j9HN1QBIro=,tag:eURbN+2S47Mx24xgaCPbGw==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:2HGWoaG9Vkr/7OC2iKZ4,iv:tNpfqOIjG0HTmSJpWOMO5NbaAex/Y+HQdMm9J42bAxE=,tag:xHMLwcSMVWo1ueTctLS4vw==,type:str]
    #ENC[AES256_GCM,data:IyGzC8Na2Bw3dQExP38sBgX1NLZZ1j7CJDEUiQRSo4wVwRUPH92H7NlBlypwd2E2oWnEW7Ugmcd97ueJsNbGoCsOLA6ZD6GhmYYWanp/Pzc=,iv:bgiRQTexbHeWsDTu5/J2bFs4iDUw4XRuysWQ5EVq7AA=,tag:tYWpYT2iVIm8DLRTB7mU+g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:AsLTisl3/BH6WlbbdVIL,iv:0QycuPZc0DxjMCkyF6nwe7DH2BFQXYaBSlrgUe224Vo=,tag:5Nwe2LXLbd3VQ5eEPjj1Gw==,type:str]
    #ENC[AES256_GCM,data:L4a7JxTH2UACYVIzHmTI2WzKEUkW9JjiATWNbKF2Id9gu6mGjQMfuz3ju7ONXTwbHYVDMDLeJdVuXcJk+GG0dL2lmd6EoT71Ha+7+x6suRS0XUEgl06R,iv:LXxhXWUxB3YYn/3VUi+9NGXfw9cWHEXzvTsiw8xrwN8=,tag:9c5Lbk8BjkaZsyD5Nq/R+A==,type:comment]
    #ENC[AES256_GCM,data:O8gC/ndvqor/UU4R9np9pQ+KXakUdU28J3pMjthVth/AMQA2IkHwC3D4f0ElIeMKA+ehV/uCV+eymnXk9Xv4L53kjWRNTY6NGIH8MaUImi4D4Lh2o5YDlrQ8oXVY2mDW2/hpPQTyOmE9+dqvAR52aCLtIfypwk/rL1MNug==,iv:6VBZFKaXzmXCB2FOTkiIG02tCMVgiWh4JsLtwXao3Og=,tag:iHlLnllQ/21aiPBgnVvb6g==,type:comment]
    #ENC[AES256_GCM,data:4yKrpWhEHfUqXkVj2TAqKndCPBnj12Jyo+MEQP+R2ox8WLZsDgjNtZXlB+gGLoY1FDWnUS9n0Haygbj2TuKsONRyaMtpzjENSeWMG/dPgI4=,iv:ybUCNxJ6XN5VFJPKMBBWG6v6G2IvrZKLHrcSaYNN9Gg=,tag:iz83UTbI+Rvj3RNHpZOV7g==,type:comment]
    #ENC[AES256_GCM,data:w6uCLk2PlzZB89QsEtOyC9bIPZtEH8vjOKZzDOEGHWJ2sXSRQUE9/OErQpeFs3IvMSu4sEcx,iv:USA1wlb05ob4T86RjERqlU53DRmz0h6dWMpRppwyXKM=,tag:ctm7ujnrvLetIfgZaJJFyQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:Df6oIqqvmzJjVBok,iv:N5184Urj94IS7ZduRDCy8ranq+1ClfQT21P1Ynh76s0=,tag:jaMeb868RISipLWaIaEwng==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:XKdJ5qNtXIUtp89v83dfoDo=,iv:6GqKuvawVjke8ILOQH3ZwuQWWy9AR8Xq8L+bcNv4+Vw=,tag:MnrkeKdUqJoQs8LiOnpVzg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:QpQ+itNSW3Ial8OqWmF/zYq8nIff4yPt4LrOLNRdIU0zzBvKjjjVOg==,iv:vnCeNyPwsEInkPRhX7dN/FMPdiPl9BqwVtKmz2eoLnk=,tag:kDZpZzDB3ajVA2e5KTI7oQ==,type:str]
    #ENC[AES256_GCM,data:cwUjEmzWpKq1qdddzfsiWN8rVtfxvg5DJIEQOJvPO8ZbpHCclPELTdOJEUQazejh90ngj0SMkrc=,iv:drMg5Eqqo93PjO5VO/5HvpCml3W00skTbl9fhux0sVc=,tag:+GIzN8rALGBAAl1tpLQmbw==,type:comment]
    #ENC[AES256_GCM,data:hbIjg/B91TK9nAGHBjNFTtIrviCHd9Ze0Q==,iv:gH3b1CTZ6jEtsno+E+5jYg/omMbQENP4WAaHXQEJMNE=,tag:PlguStGEAQ9T95KKg8fipQ==,type:comment]
    #ENC[AES256_GCM,data:V5lOeQKxkQ0LKh5rkd34FOdBaagNpFfC0YCX6vv/8D05TKQ+7bhZf7zwHSqxRUJgDaIL1G4R1zXSPRhaXnc2wcowDyMOc2p9IrPLT88=,iv:BfHLM6beZd7IwDvPOjN8TAVM7gn6VvUpb7lfitoZ9Pc=,tag:F4advPO/q8XQ+K/4aMcXcA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:7IfV/Ky15AUfjvNnpiCaQkfjUnvX0+6tnxRlo8UaGQHCbveMbI8MeMq2PTBsxkZR,iv:ujB9av2wkqWWvmJZiBHpqmSGs5wwjbm8ApS31ZQJ6E4=,tag:VUGBaHdANb0psClqeVrTCQ==,type:str]
    #ENC[AES256_GCM,data:OIzS00+USZg9mdvu9R0UEwYj5mnzdg/b6y9CsTXuX2w8vrwJlptPZAElJbp0+m1f3BStR5+iTgx0moMZtCXw2oLKtC1Z22A=,iv:0gvCdd9OFwHv6UWpubOmI1uvt77nVqesg50fELqmXv0=,tag:lHJnBTFEbkFYVPvQkLVtXg==,type:comment]
    #ENC[AES256_GCM,data:T1Gu5lDI62ZtV5e7KOH3y4e3AyAYDuLDAAAVID2NHmgrm8kqxXSZQRaI31nA7wdGSLXBwtnm,iv:LAaYGz0wPDoH4EB+4h8qNSi+WoLQoUW7Hhqu42GxR0c=,tag:NInzTNsWSfa/NOQpFqdpxQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:OQv5idP0qg==,iv:N3zFBY8q8aq+0LeI4/qOpFhaBjKeogCwTmxVmvEASvY=,tag:rcZELe2/CtOFoTEMAKaWZg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:RA8Uf3WfbYJpEjIscmpWHzZxHrU=,iv:UEWIqkmlrWN2/821VPW0Y5hCo+sxw8kjaKNyL2jaJ1k=,tag:E0/9V4UmfjhYs9XKi7ylnA==,type:str]
    #ENC[AES256_GCM,data:y5j/JXpHmnE4VithsVU=,iv:wiHNK2BWuMJSfjekx5rhJm8o4MptI34xE8COgyDW6CA=,tag:zPUyEnFDOIYDmqsVkKnA8Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:nIYEPZnT04hvzLIdlg==,iv:taVOSSm9zgD8+0YS/qJ3rUgDIhn6y0nOuvsdT7TZnxk=,tag:jCwj1tDhJbMcTEO7wS0mOg==,type:str]
    SVCNET: ENC[AES256_GCM,data:MP/AAfxC6Jx/ukUrEg==,iv:5Tj16l+tBqn7JntbmGe0DF/9gPCHlGiJmkoMT/SI3D4=,tag:xzXE+c2Kv6Ds9DUx6sezKg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Xnc4CA==,iv:Ta/evOFvp8N8rGx8/3qmtEu6wiKYN+Dd21A9pDjoFMU=,tag:9q8YO4iVv/+a6rPyGOXChg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSy9SWUxESlhmOTZtVzRa
            SVZiY0FHdU90WkJOS21zN2VWaG5BRlIwSXlFClZsZUJJTVRSdHRwMEliRUVqZTYr
            SmowdmNUQTdONkZxbjJMb2ZNbW92bnMKLS0tIHh3YjJLUHBpalN0UFJvT1VSNmEx
            R0g0amRLZHBDb1JFK3h0SnNvZVBTMGMKmUuDSAi/vJf0UdxHxGmGEBTV2QuSiqCF
            CqXKM6NpIWkaA110qODPpTbrrLPpHc6VFVhT9DVTxoY3hcYeyX/PAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T20:48:44Z"
    mac: ENC[AES256_GCM,data:FrNVZL8HzT2ewCOdjjA78FnCAABGjE5RhmGuYkkZhl1fSL0OGy9qvlpKN4wHjOwAaMzXlDU48De8QzuG+pBTWmAuT2dY2WLWM+BzuDEk7nerd78gXEPkJfQJmajaEHOnOJ4fpkRvuJvizB0GHztgKo4j5Qf2DGIDIrYGskbf8sY=,iv:wm468jTqtKNBtqq5V2q6RpbMSSu5zIhV3WW04G72FlI=,tag:mDp+p1Kzac8vLFQfv1edvg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
