apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i1Un1OT4SLMKPwphpi1oGhek4vZRw/42eWYaVVOuuMW1R4Z71aD4WeVhzBzgdezkFXWoww+xn2+4QH/4YkaHks/RY7pF92nWZy3DmFPbkLnGOfUcF/vNlQD9sG1F2JpxjwyJTz1w/lB0BFgNHo+GDmaNNOk+C8dpLnzz5mjqtoDNCxwYN5QGu8xBUCb5F7pQd7OzOF57768wgipMSrHptP3hYhQIPM/ldEO7KenesehUcHJAUCmbVUHtk4w3LTA1sibEH4PZRLBaViu9egCEP98Mf16btIWCLiAR192GvWfkaN58tXrDEMfFqPyD/JmvAg4WEiI1O0vkcxPq3kkr+ZsZDMZ/PmkNRsW0lHMQ6hUutxcRXxOUM36VOi/gIx9e,iv:FB95LRIBAgrxh2ow4BCjfv2PNkAjPGia3JhpTIv08Ug=,tag:apPhGKPo4rJlfSVVoEqfcw==,type:str]
    identity.pub: ENC[AES256_GCM,data:/3fL4RGSLFN6vxTo/KyyV40rmWsPvqeGgfPyhIFSesG2AFwu2Z9WdQcmEI1m73X252vd97Wp/CbfU1IgykN152WRGbCEB6QU9+K81pCA3ecLrPAg3AJ2iMFiholmJKYwC/Wy27Rdq/q5ApxxRXH2DPdi368PB8kZ7WTIi1wcKv8LLzqUAzfw3TzmeFdHe5LQ//L8gMiCXDEF+6x9KMpn7UjIfvHmv5DNvowQkYCP6zYkQMiAViAMQkn6NTE2dxME82F6jtINI/jXuL9Dkw==,iv:xP+GLuLzFhUuRlNwUWaDh2nNoLzLZFa4oyly+4gr1Y0=,tag:+JMDyOv4CPTG8cygLgHoeQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:6YxmdI8Krm/quzq25rDj8tbExrpekg+QDQ8x66HMcqAh0lWYvU+7i7BgQK6mqpMoAQSWx0rwLW1/Bj1jrBaRFgmkNOB+FMP9nx/jiqaHV/dlMLz6shnmR2u3A7EqXx7Fek0R4Y16GAuXdYSf9lw+dTiaVB0OtdkBaNP4RIIdIa7RK89PK3AGn2WES2RByGIiQeunmGaW82JsbCn3xbFcsVUxk6dR+8fNUR6I,iv:qAch/XjM5Gk7iEdbIgYp8eiBteaopwXp/dj+AUOFXs4=,tag:r4ipk+fIrfe5AecdVz2aXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeDR4Z3FlSkg2UzNCZU1T
            QWk0Rld2djRSRU5DYmhoU2pud2h2WFQ4SjNjCjMwUjhyelp4QVNHZ3h1MVhqOWsz
            MjllK05tTjFjeVJ3UndMdXQ3STBBTnMKLS0tIGVpWFp5eWRHdkE2amNBNWpvL0p1
            eklub2M2UkMvNWV6VU43bmlGRDVxc0UK8uiyZAs666xXOR9mnzw0rpKYy6Dq+tiT
            lZNZPRguBF0IanVkaqnBhoduXR9kFuFcCO/Fltb4NA3K6jUizh9WGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T20:48:44Z"
    mac: ENC[AES256_GCM,data:W8ZJyMSA97AJ052ZH69dFmcswIMOvjkbwWMb4zuA/1as7clXVZJZRPAOFi4kVHrvl0bmWxteuHVSU4IHw5VODYrTtWFlCaqkoOI5wqKVW9uEPQwnHGoRpxUcBt2Bv0qsjXCAa0WuiipFFUNROk7rDs8QT8INYK7Myez2ang/ZoQ=,iv:AmYLv3e3NpufI6xuM51UUA7Tpf3fT/YYvCIr/YfzC6g=,tag:XGw/OovuKQTeCQKEA/Kl/w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
