apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8dXLLUPC2cz/W93617H7+4kMrzeDvucHNaVB4SzPucRSrwcAyDV3vrMmmf+XR5ZPiisOhUZe5KSyG0X1JXuFv9jnmjNeNdFZizhOy+ZD2eDcWGZty8DRxV1pCldDhQ/vYem5k22/C6dRlZJfDO/gcQvpHVqKQHPkUQnbm6o5Bj21S4y9T6+TSfH/cnCwmk5eCTTwo0I9OdJlZIvjOZ0OIEPU/anMXLLl71E1zdUso/6Farp8OvuY0ZjKcF8V2mknTeZ4loTdmo3i875DmVqcTqjP+nCJDxGGRx7x6WkA/qdGVlDsodGwHmCaFnXWmgk4IaD8e35rZ3KgE5Oqg1NTzi3KKfecm7U6iimrvowI+VPlbgpZSEs359houKQcZONr,iv:G+7KEv5TpkewkZHCoOyv4iKenxGyY2bGZyhi6Cz9zPQ=,tag:alWLUYrRae28yx7UrbEL/Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:MV/q6LNwnmLJ6hvn8Tj8bMh0LS/RKTPgDSIyxG6TrJAcsc0FX/jAlhDymj+9NufeHpBuTsZUrdte4amfR+i9ASM2egjD6jkilliKFosOUbutoD38Y9X7uT1ZKt7aNtTxLoMkVyyAi0Df2BzZmBFd+tjLZ/dlxpI4pJpAvMTiOJDxhlN0wImUQDvYngOkQdMnRizX6miNB64oYhZmWJxvEcTs7AgJ8yQRRnGZXB1QiPFi52l+CmnwregyMOosFNC/0eb3Su+0Ml5Lxxkrbg==,iv:0zEHntzefKQY3Yt4vKumXN+vXH80YH2TpaIyluDnYko=,tag:B252i3ePUsC72jM92Xs6wA==,type:str]
    known_hosts: ENC[AES256_GCM,data:7E/QGU1lhG5Symh2ZNhCv5bQULsq1xQNEtQHFD0ADxfXEWY/sr/hZuYdq0VZeeyjKvHyc8l7UKYnI3pxJVGrGCDVhZq9yRVtALLYVnuyHjBIyCHXCUsPocK9xa+HXYsMktz9skHNBrBCMOBN/eGivAFrozHMflffzZmTRACb1KIIfPlVlbBDxg/2cXOln530iac0mv+oOs4x4XLwTIJykxEumYIBIOtqMzgF,iv:5yt7vBa8QW/ra6WU9HWuOKAaQp+rmDgKUG/r4FPmrxI=,tag:ghS3GpgZnT3O7IGiH5KfYA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURXRmZEhRbFRWMkt4T0lo
            NENucWx6Y2dTYXNNN041ajFZNWtmUkVCUmlZCmhjTHBjOGVrVS9yYytFSTBDSHA3
            SzcxUUZLSUR3Q0x4R3lSVW9QZGg4RzQKLS0tIFkxcnliOUZvM0NGRlg1clhHVEQy
            OERYdFBGbWZpcEJiNjJVaWJKQWRPMHMKBHlhtgwd5TwPh9MXoRD9j55wcE4rUGdL
            hQuBVJlVZkzZ8+7UcsH2btOnjUpGp5EJZgz48ZPyZcVuCm1Y9v9QeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T02:33:50Z"
    mac: ENC[AES256_GCM,data:8qdybFC53LSI9CYLyvRs8Z3J67z3rC0hV6cxPGC0CgeDiddWFtihyQNPbLmNeMaQRQLvShe8z3k+CZut8FkaJ+UMMl9OxXkZbsi6qu0wGjigMKc2nMEZkp3+nKaWhh+WTBhEa9tTBlcCr5g5/66uzCJ/HgcgGauvla/zhN5zUAY=,iv:cb70fpxJ1BaI1GoJNd0ba2dE9pDmOvyWJD5hSPqiPyY=,tag:5f1LhtYXKvqZkmOvui57AA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
