apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DHoOovDB18hxKtawHRjZzWDO/93UNO90N5Ghi5fXx4C0iO2PYB5MwZ2Qux+Pcx3yCQcsDCKdblX8+UHilv9zvrW1m45MnvuhruaqJhkZzX7I71VM4EfZZi57FF8uXZqbxnINEYrjihc58OpezGx0o8xO07nMRlTfGaETIHpVfFDwbDMFSEmdW/MHCU2jhJzCbs2vdrTYkRCbXO3hjP+4XeaYZZVqRRRhxZR80Y2lVgKKGKN42OymYrnrtWctHmK90d/KKjnRnriNOdmSK0yaWPghPa2CRmCVSpMuqfHWnXi8xiL7jsjOUSkxR+Lgh1SWCBP/7sCvLD3FMdv6BD8xUcud0qYbybngrOXOZ1njLszaZGTfYMDYwmSUWzUhnyrR,iv:5blReQ6WvZSr6AEEVD1Tht7t8pML/dcQeUfwZ1JIt/k=,tag:EA4ZfhoPWDVWlkP3uT1Rgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vwTmXZZMWa8y/YyKSLkEqP/VivIEDzBfqrLwdrhshXpREgn2MYtYOLiulSPwj+sfB9+SyC0l1e1yXty/GjdrtCgRVgWA3zsaNMRnmmXL68BmMGihyQyT+W0kJMElNpELDnhXkWSLpKoGTAGtxcowVz8J7Rtw8pO8iIeK9d81+KI+wLKG1DGJLMhA8MRbCBhzG9sZFWSZIyPRu2J1NTUErudZb7mMygdM4hTyKjAEfqD/39QQ65PLQRh43eNXGEmu++G9AZ5KZBwpE+vFSQ==,iv:wI/IrUtyegC4dASE+dQkY6vXlYptH2u3lPod8R1e3gs=,tag:RooE3ayL9vk9R6QE5qSwHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:F1PRhkak+oEjdTNivt9jDDkfTmXObnhw6yzCxqhIqeAecX2sGiwGQ80wIoRVw5l/SYLvVAeeEIzi/mmvkg0jxw8scNq3TyDYuaL06ZO9XabU40rGR+kw71/krca3jrxaSXH23D/fTFPL5B3+Bco8ULsn+YFOxy31HMw4OQ9uCSRsspr1PEdQIJUCJ23p0oJj6oBY7gkjU/cXlGjHqD908yNGjw9tRUOZWPXV,iv:dZAU7mMzeEvVRWIvFAwJiTaFGlT38sPx0QiaY6UpMTA=,tag:ng0eGJhy0IaWavRawmlCsw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV0lRVVUvOG9kRmNQeE1Q
            TGlWem82NThBOWlNMjFDMDZRWkIrbFM4YlVJCjh4N3pGUEJ1SzJOL2dMU1FsbU5E
            Rzg0Qll6Qk9lVEthYWJ4VmhkWUhicW8KLS0tIGk4L0d6T29SL21aNDM5MHliZzQ4
            bjVhN2ZqQ0N2NkdpZnovMTZaQUs4enMK+AJmSvFcrHm5qGNcVmSqdfaaLO+a+nx/
            dzc84eJDnyl8xRBdYJHExiO0OI2POb8jC5N7A0yK1tBaTZ2bwwU8mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T22:01:25Z"
    mac: ENC[AES256_GCM,data:ToIWA5PF0acSC/Ya6ocl6ingW7Xr/q2sicBV6GsIpu30L1e18Qs8cZ4fhDAzmmWbVn4Pvl2HDJxZPP65l47JRc1PLCZe6xso+Ky+21H7v+bIcQElXfq2F/hbB2IrIuNqtDfhCUG5hMe+BAfGDqFrDwLdWvIZ9n0527WMNA/Ljgs=,iv:P3ozx2rC/kr3Ejm3yz1nEzybhLMdvO+AW3YL1sRNXjY=,tag:MY0d55XLo9LYLLSW+K1j4Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
