apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:n/sv6vh1pm5lXmnUXchUSsuYuWXosYAyNFgBQFDcRvA1MxIF+WFJcyyHb/sUBE5cfzbKCeG5kBMsfljn9YSFd7zIyGX8jlr/+KRMqW3mIkx4oCDxsnNHUWgroEb36Jtk1WzuUCKUHs+5eGOz2HoEw9B3EpJHTTEsPuPbtM9rQbe/HXye0RgBN0lKcZIAS0pEqKIbj8H+Pfedpjx7xXXsGKsNtmV0Nf1WS09CQYXgpar5YjZvfBVAN1QxmQczAJhSziXJjkpSL1N8Apxcczmp1OTupw8/iRAoi0dnXMKEmUbszCRqG3ZZrKEdP+jo9ZEX+nVadSeEsfKkAHptgRWn+5thgQywXypBJiDDt9xDCeYt66OeqTJkBxQCVhc5BxH3,iv:YYruMpBAWaLZBM2EPGod7Gd7C3141mWbz5+aNpxooFQ=,tag:RAGj21SNlntthA1sudaEuQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:3hZCQZL9ViWVoOole2gjecUovy39ajSpw76UqwsO5Q6z8/zSyv3U8kn86ucz2oo+mfZciQ2kSD7SNa4qvxp5fAymVdMnNHug5Vv58c3ZTlaaKi0Sc3DfZhEw4NT40DFYBQ5MKzzgi/Xd4Z3QDRV92Bs7GSoWozBWQ6Uk3+gEynHH0y/rZqUgQPoAeVAYs57LrjdBAUZpTXJyKUkPE1GkpS94mRbeFiiD6RTnYOz3SjRklI4hLY4qihQGdIWyOtSc86Cono6fXDdra4U8jA==,iv:BpZXfxQ202bKxaBeXtRccXKgR2Ge72kH/kuOaBKMGtw=,tag:YtnLfwQ3ZsFkhn6tIn0LGw==,type:str]
    known_hosts: ENC[AES256_GCM,data:lns+v4J0GwOmWWZZmvPZD8uFdsCXic5Pg79M2TDLo7kfNHqr4qgEFQNTouvoHRq4MsIplk4VnGBILrbhwUslpIF65fVtjc14ZtcYkPTHsFlDmcWd0MbVpluxWSJ0x+IDw7dhiwHiDd3FGRDwS3CdU3oVJArzyw7OUs3WztJ4zKgEPkt8ziXXcDMAI56a3SSVmLqlHhxGVckoLSHW6a/NWUdSGE7d+ja4LglK,iv:OISvzTNN27AbtaypCEs8KXHjKFQN5qlrcBzjo+pINeA=,tag:ZV7cLgRFOE74sq+GRLWB5A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONklWaVNsY3ZrME5sRnRl
            UUdHZENDRGFEelpTUlV4cGlkcjNWMVJrR2dZCmhwUzV3cE5IMndPL3piS2V4YjZZ
            R0Nac0ZnWWR4YWJsZzBSVTduTVJqQ0kKLS0tIGdDenlDengxQWREVkVJMlo5UHlU
            YmI3SEJDaHBncnZUYTJ3YVNYQ1REemMKPHLSHjUBH4MS5twzu9H8P+3qH6Sx02QO
            46AsGwzUDwEZErGDuigo0LjHYE3SEavYZHKHqDojx+cS/FC1/fsYvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T21:23:26Z"
    mac: ENC[AES256_GCM,data:5WlnvGUBh0ZZsfqHRJKX4S4kJ9NO0YEbpRKMgwakdR5aK4rSPt0jV43qX8ImivCw7xTPQIrL4OwxlsEM3E+t4LITaAldhKM+AfrYpoiJpe+dmZpzuhoj/h1xcKHa33c5bwd+usmCl6w3tKgOVKXwxS1DcaIXP2gi4aYNjEP06ZA=,iv:rKi9nNAqRq0b7Cq6lV7GNhwHEJG5EUYgu89XOi641O0=,tag:CQLaUbVnsRU1z8SCkMl/KQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
