apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NGWwIjVUuvzcrYzN29S8zOz/FRSP4NrSAAcvQKn545JfufQw0cNO2hN2JjgeEJKWeKYT+HLDrcWpROvneba2L+LOVvQnSQCLiws36AVDWpwYX4kzwJ5UCKB2FOkleUz97Ge2mdshiXBUUMJ6eZREJBrZs/quvDOmc7huJOXRHm4yEkTxgbxDJlI61eRSoXEooYjh5CqIdK20HBzlwfoylBCmkzExm4rTw1MAafRwQeZ+I/WrVsfepIq4/wqq6wHSEY8Xta4wx/xA5Ee+rYmK+e32B8laZMlEnv/0heZkWjR7i9bEXtWOw/RbBdHXDuCuyKUNXhxSqWz0U420GfUvlvBwRDhHrpfup71FsZu6brwS7Izg9DqwBV27TNoDmgX0,iv:0vdfQM78LIc2KotN+B/O+DID9d8hRGgzaRW29ieb6aA=,tag:yHBgTx3uN1c20kR1wyK0nA==,type:str]
    identity.pub: ENC[AES256_GCM,data:1LYVQxQicJs+ok7um3R2vRqCyOoZAO7K2ZKqhb93n7U6UX4/GCVxjzRtcCcrD/VsCxB5pfqjz09Q+FoFoIzmJEbKlmW/8rHyrUi4wSJOANzU4M2ae5PTWvS9L+cX+nvWHNex+JhU0/ZN7lzHqJpOSx8byo4aDDzEnJpMdx8Lf+pRkeBuCQ5+qnlt12UNMdd8siQJvoqo7XbxEtHN+l+TQV6EiD53UtdaIRgMHwNVwQC3NZOrwd02lOBvWwwmoTgzav6DBk+7g+FzhI09pA==,iv:UAQd19IRrE4kwyRUeBH1ncByhU4347RA8A4DpwaTyQI=,tag:gpSh0nNNJie+N3E1ky5siQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:8FVpjA5+OK4ecTzR6Lp6lFurtE8striBkWJcI5B460ZuZfJ2bM+rnqUzf3OuBc8XAluv0esRKiuj7vAunWaod+wHDL/qtJ3GTLDzqhINlixnxtglwiZZQ+wxg8ESpSCVxody9/L8NVQVJ2fqeTkiOVrijLZRpqn8c7jYwyF8vCkYuNsPK2w9fWqo0gQyPjep73Z1qujPtRGKVt9N6DWIYj6/D3eW5rt4SUd1,iv:Dyo8DvnHWNfiHRn+F2NrjqYQ9fzOl85HxzWAFKwovhM=,tag:ibWzKJIj00w7IMGi++y2jQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN2EwZkNuc2F4djkwNnpO
            bVd3VzdoVDRPTmJjc3JWVjBQczNqVzVzdFdjCmlDRndCb25wRnhseXI5dkV1SFpl
            dlpieXhucVpRVEk2MUl0YTZ2L2dCSDgKLS0tIEVZVTFzbGIxRnc1RXdEbUlEZktF
            dUk2cWFNNTVHS0NsZ0g4bHRhV0kreG8Kj+UbANXKTUUVa6I8Fl2vYAd8U4X5R3WA
            2NMSRLcdtpvtcr/H/aZXsWZv1Ai9lW0vi/yz91ET8i2kBuo0ks4luA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T15:47:33Z"
    mac: ENC[AES256_GCM,data:1Jo+uLc8J0rrFiSRoivhBr+RCr0YGosf09dxYjLWbE79PgCXV9R8rud81Yy5bxe6ZL/vUo1Yo/IuQ8WacqEGhdD1bG9+ZBb8lKoORMG6E48GG0xtvRNWi/fWyhC+t+Wa+cFvjjIqsPX0YzaTme4BJ0thbDUh5isYHfEV9DZP+GE=,iv:q2KNkP+kZLYzRQfYvE9wnLunrkKZ/wKmOs0jV1zcOfU=,tag:esxMomKKt8s7Jl1vZ+sYcA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
