apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7+0ztq8MKACknzQRfqzM+csh3ADh8o77p0oXY+DI8HGfZlLJVKD7q6i2WwlVoY/DmPfJDkhHvWw/Xkxi/elDlrigdoze9FUWBVm6ZtoJwdMAP126r1wk+KA8pNwp8uBq/t6heOIOQEaotyqhjC32472LSBKIH2huX4IBwd3XLXiMQlxE9GmaQVrn0G3rBO0UOFZnckvi+sIvSVL+TQB/86Nz7t5CdEnmYZheLRLlX2UcfJGfpIEl3sMk/bRQMSJuIxdiSCLUYaRGZ18S7wK2O04Z947sHSU+MwxZMxZASmk4vKyheKtxGPJTlvBLvlg2uynupz30lpF9Mq+/MVlDktT6RS1vVyUMtIxIwFb4qYmoFH3Q/EhqPO8YzcAuzZ2V,iv:YSEznjZRSYp1me79u8sRG72oAlHpU8CRBJ9VSC6dM0g=,tag:+4/Ajr7ObKkDlTw836+uDA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ew6JikjgO2nxeJJa2/sXiWyYaYGNQZVTVZIy73PSAqJq5roGtjOr3FUnqOugfD6M0b6XtrXEoGS6K678MkXgMeKBgk/jXcRAL04K5+7hUY/Ppo5M/d1+gmVcvIccOLw46CamKeq6WBRzsz+6KIift017DYSlViPO1bL89X9yo8KSIYDHyf2It9b9Je130ZudHfwusGnriI+D7MoXKpOEtPK3TOVwoyDwMRT+Ve6L23FYlue4tidplLteu7BFTRhZWjfCLPBa/YIsIW41ug==,iv:vli93ShaREbuxHR7ltBYEp52RjEWB2j8ciBzJastxGE=,tag:DuWoreTOH1IwqMGLY94DsQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VN3HbP/OIVNwMngHPgL7GXOzuqmAld4lJu9h68WDgKy+aocCBNWe4zTiIu0ksYnmUqREl4PFDJ6HQr8l1DJGwIqU16pKU9kSTqpc7YkH+P6om6SkujBmcWZKk07JStYvGtNY9Iexb/Hjxf1k7x6iVhEfR17wNWhC6lqYoYJtejrhLm3320KRCtCJ0UshmkPqm1OdxAWixW1HvIKh3tXPOPZmQiHdf7XexlnN,iv:S2o8nK0PJGmTeOnkWbbevbZkwkiAUC94mqZD6YuDBqg=,tag:M4zdvjE3m6k3+R+aXFVw/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTg4b1dUditwTmZhK21V
            MnM4ckNaOG9MMU90QndQWnpDSisrQUpHeHlZCmdHTUMvbllXUmoyY2xRc2NlVmV0
            MDU3RmFwRWpiZkVYeU5QVWJQR3VMcmMKLS0tIHdFbFROSWhTYXJQeWZuS0VvOFBH
            K0J3Z2xBYzNqMXh1M3lDcXlsTU5YdlEKkwDWzKeo53hHENeLFj9aV7kwure0IaIc
            DTUuXcjFBx5waW9cvoMwpuW3FRipQpj1X0WbQVLJS1vs+cR3ySNnng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T01:01:08Z"
    mac: ENC[AES256_GCM,data:0Z/pB8LMMqDM+rdzrKFsnlt0TgQ/911aj66ySscE3bgGtSJWfjqHJ8qOcxUp0SVrFRp1iYbcp4/3SYTGH5DyEK6UT+Sm0+xM6aObRmAp86Hfx2lh6dfZVRKShfAvNz+EM/8nAUfjn/OzGNP9L6MMvMblKhtBWipWDw6tauOowUc=,iv:nZJ9oavGaLw7wPHvVVFapzuixYhZJkHJ8iWWh+yBqg8=,tag:FNI0S9wSJkAE/4kJ7IcsYA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
