apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WxaGJ+vjATbOIdMnSHUCqdrvyPJNmP9RWGtn7GM+8taFw9FpeH3DeYv4Dkbm0nCwQUWTNdOcokQxjyYBvf2VzdBRL5K4E2e1VgoXoj+l17NNAykb1WnSEskRY4Hs4TGXi1tRsz19IUQT19K3063vKu0JUz+A9Se5PPB/IaiYQaead4nZUxn0JbWZajpIbnEPQN6HStMT74jRRQGMdvru+0iVeePgvW3ASmx7KLhcc+0ExXzBK3/yQ+07W6rmj+HMGPpWvHrH0684MMFbjgwQ3eO/Algr9pG6Kh0XwbLPuuUIZM9O6L0QWHyyPjjOFotW0q3/MAjfNjYV+VGINZyjjnlQfBZ59Ct3et5mKc/ocYJxLCn5RE887MQTmWoiHm9u,iv:uraKVuGh5AO8jA9/yqABTkBEB/xg8bk2UNJJJ35ePOQ=,tag:WW5ghFA+XkJxU7/0zGfmVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:i5K1Htc5dK1xM6xWiSK5lIARfRThN+wOm6E7RR8X79Qf1sVMX+yBUSxuV1V1MuQ1CSzno0HKzIBAojsE8o5Kv/ONDKKQyZydRSBITZfKC4AdLiPv2peyXQ9mFEQTGTwbcKiMHeNiF2m2By0N+yGx3gfD+74ZMa3TBP0rBYIWmKZACPNpPX8umdKjnGuSjkI8GC0snKx0ZQ0qzbpYPGPlOv2LJ6muOp14RdEsGwTiHMau0ydvO9IYodG7704BV9qnLlt98ztPxt9honlvkw==,iv:Q1+paq/oAAOlbE+rgZ5g2LveLbWT+JqfefVNTY866WM=,tag:oAjHzD+2piw9YWNkAbfYkg==,type:str]
    known_hosts: ENC[AES256_GCM,data:G9/NeSno8EaiAHvYsdbPa7F0wDdJcsC/ADCuvCIcJc/Ez8wr+zNVyld4joOkOJRDrem3hCgdArgIOx4rizyiqBMJOXXbIkYTd9gbfL+aBUYx4UuqB+EhuEk1nHdksl9obt/nl4gqp8dYB2Zf3/bBzpn/T6gnPr2TrA85ckpPPw00wGiCwaxhs9n4iF099ipQmVEoUCSWH7KX1AdDzCvVP1iML6wKXFolsyf9,iv:j7n6CEGOgOcXRkUGS5NhhDaT9a3vZQdXjupkdG9SFsI=,tag:7b8DTK+bO4OiA+g7OOt3og==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bHNrK0YxUEtPYnd4d3JI
            TGhKT0wycVNOd2owWVlrR0xmYmlWai90eEVNCjhhZytUbThxdFBRVG4wNDdmamJE
            aVlIVy9pNVlWbTZvSTZ3K1BldzA5c2sKLS0tIFNRdHJ2Wisva3EwWEJMa0xQbnUv
            UnNvanZrTm5UZDNaRnkyN0pEL1JVT2sKplIY4cLIL/a5rUZr0kN3SZNMQepuNkgX
            DCb6jiMLDbnETHrtX79KYsGkfQGp2ejfUxTUelvqM1E58yqmN9P2DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T21:15:59Z"
    mac: ENC[AES256_GCM,data:KLPl3vkxhYqFO3K+6l+ON9MCO3GLTofuAE2HOp93a9pOsN+NWtaKy5oSmo1vEViW9OJLk+X+rOHMuc5j7Omb4De33ae2Ku7EW1Dl/KcMh/nObtVFdbis7q17uqh0mPsFnecUX14oSdMn9WWiHCLvKRLxgIrWJM2KUsA++imjTCA=,iv:/MInb7VuODalQW6XhxJX/KeRss8swKeLqSrFzEdAwMk=,tag:qCE3NU2sIWJckdJbLf8PNw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
