apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nfvmx1stuOJhx4uBcZnmihm0QGZnpSsUNAEt1SXIy9TLwiIsQ9TxrJQ82+1Do5sUt2g2FnjJex73PfMkSgOpkwZtcTlQteP+br904kQ0laMNmMz0G3F5skWUEUcLVOpuCcRrOlCRiqoIqgPnkGG4docICKCjp9nTbtxIb9ph7S3SQzG2gcCETWNasIDARi+2d1Ltg2xcZqPjxfFkMfFg8Kl3dKNJcozZv2rwq9uO/L8GZmJod9G96cbdwh0OyVU61MBW6XxIqNioSUEYaXET5z5JaZjG2YiH0gyc8EZQZ00woqDfbkYoJr+tplhKZ/BkEvrt/bUJgxqNqer/lz5zmGVDHIyPfUzwBSIRBk8EqzcCIfsiHoX98MLMHpzqGUMA,iv:9PFGOMkWLbaY3YUudKynKu5FNhYpu4h/mEfi+CC0oAU=,tag:Y6Cc6CjCSUogFuh0ehxHmw==,type:str]
    identity.pub: ENC[AES256_GCM,data:P3C++Gq0jSUbm/XZdUlwrhCWCW9ejsyOI9qmWrjfYiyBU/EPFKT+HGRd64gN9D7fFC5vlZ4TgJXocy4Q5+IhZu1ij7iH4nKHVIflZTn4a1shiCGsqZhHf7h/1pMOyrjp5AKDGRUytrTNv0bAiXzLKXQS2bw4jCkH8enZreBikj0zjnyJRLwi6hocoGOmQ1qkCBkYl4m634fE3Y6tLgPUiGxZDD87c/yHdX7S+iy40L+BxDdGoozTvePdL0zRtQ1DZf4g0I03tEClJz0UjA==,iv:I2EHmLiNLw+ohR9Xv1dmLR2Bf0ooOeM0JtmsWxRGQHE=,tag:rjGfNkpT+3SHx8cUjVifiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:QTl61xUngWsz5kAjCoNeC0H3QrBEe+Fy6QVrD2WrKsashFKqirw6TMbzcaHjo2fuHHzY6VqebJLJXzCNbsvLjLdOI6XsmlZU9EdPN7rPrO+UPym0JpSsBwA9W1clhawO5YwBcO5osf6QI2stp5RXbbgE3+HTI3B5S3RVjiT3ZLVnr9NOqMU1g2XabUkDV5hEr0BzATo2GNx/g3wB6Kx3K7KEuk0iA8wlTqA0,iv:FH+YSoRDvNE9hBfWuO/UhG+G5yWYX5rf1Nq2mqHUKOE=,tag:8nG+t4RhbhgogpskwIPnbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES2dpQXhOL1kwR2lnclpp
            bG94bGtycGpydnBRNXJnTHJxUU5OcTFnbWxzCnVYRWF2KzRpdm9ZVUZZTGFRamFy
            dEJlMWpUOVhEOGJENVBoY2dDem9YVXMKLS0tIDRyV1BVTkordE9NYzBEbEQzTitG
            SUE0aUdrY210KzRvQjJaM0FrcWUzS00KZ/mqJ+k/4CpWvkm3sh5YqV5CIDpO4S2N
            FBYofN+ABd19k9CHYosas8lgeY5DXxHWWnHxD1NBMIcmuh9W8sfVdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T15:08:00Z"
    mac: ENC[AES256_GCM,data:d8YC0lkLACjcdCEALRo+vxZ71FImCyqtphMOP4adMb/IQ/r6K3jRuls2ByrPvNAG7/JbsMN/oBO4ZvnmiSPicpNfmc8HvDNarPQb6KSuKDTOhY3zp1R6ylIXkLbXuE3taBsbt43fwfzSWhR9z6Z87hoPqb4HY5Z/aqPw24TVuSI=,iv:FvlYOpLBiStM9hKzhpHLGx/OAgnFaLkoQRcsrm8VjMo=,tag:KIigRyGKJ+S5TVdkk4cDPQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
