apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Q28//rUTEPgfzS8scm3QEYZcZwrMPfW5EoCwYxe22DMwNX82QrGsH8KP6JH9qgSVebqdKXSilnYPnyYD3wwk2QcowJA/dPOl5iKUwLcyB3robkXn06E6iu/garZNZRaWQ0eH4aAFgv6IDTvb20soQFwFDBfBRUaDA1aB61gg4yyG2UmgAxQiSUexlqGzspXYvDklq6Owx7sWp8MMdLOZ+8kd10GpOcQ880NQhP/GAUf1W6ZY1K54IoJvMp4PLB9RtuD05s43+pSvNvkuD4kz4q5d/2jx9jsTsu59xRH5OZiNdTvHAbBDbrp5Kd82Dek4gRKnpHbyu9xxA+UprqZ3HvCp5RSfZMbgYC7NtKDEEwM1qdA97e4BWm2Mi0rrjbi6,iv:0BrVEIN1O9KsLeKmtopyumwuw8eydUy/ylzcrSeLUVY=,tag:QQX2xNw9R4acUjPgFzXXeQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:wP9/d6OxiTjoJ95hl0SXQrKWYyA/KoVknLa8Bl8D7DOoUqlkEx/SwArP3qa5mScWEGsNRCwsqHpbJLejC8JJiMyj1ozT6lV5XEQyP800r0cL7RpvUX1ATdimx0QU9A7Fs+z1UngLeQZ5nR2/qtd1UdFwyP7RvS5nrvnU2QjRcUIbHsvlVELYjqRvDIHodzDNS1qm2xeVsG60o9cLHOtK+KRvSZ5o50tLDDkcmIE75EDuCHn+qjZJ0Zf+RkTCI7lwbG6OgsO/Ym4ayd7zaA==,iv:ehYH+6l97QJtQxS3RSKGpj/7M8ky9AsJ5G4vg/0pz1s=,tag:juWVQtCTnsVsYSuSVvr6wQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:jUdTrSL4SQUGVnhemaeOC3zDZLYCJ3psmAnZJtOpNNHd2k00d7r46K4zWrzTN/2Ldq+9POx39/E8gE7HC3IqwN6dM1Nrf7HyPohrvAiA6sgrCRQwzuTYfvKSnDEE3QQ8cDWlhQZ4llc8kU1jOvkGqGLO4qSTIj1eemKv1/FjfSYX1sLqNGqyGINbkTrAQahJ15II1Kr5zLsEMfLtEajgaGS6j3U4NZlqNHSY,iv:biIDXVsfeCVdznwptxAzEssfbMDBBVsQrDIv65/+2dM=,tag:069olKRFD3Gs4bVO35wxNw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ1hhQmRhRVlsa0Z5Znlu
            NVcrdkxXWXpjUTJzaVBvVEphd0MrQmFHTkI4CmJFVjZOTWNJNHdKRWJMMWY3RXBn
            bW1jTEN3SmZsdjFTSGtSUFQyd1VJYjgKLS0tIEs1RDhKWERaWTVuQWlSTy9kSFZM
            SUZhcDVmOU9MZnl4RWxCYXAzN3dITDgKiODdg61s5ToiWAYROvsI+Z5MCubGwX+l
            kQ0tnvyGfo759i1RfjzOYrmkcnD6aXfGrekC6YMauwgkv+q8bvSzAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T07:38:02Z"
    mac: ENC[AES256_GCM,data:764dXlkgz28fpN642makZdT0LKgYzEkDvbRQPJvVdT61CGEnYz0DpxNX7eATnvWKeGls7fJ9cX21wISA3PeeodfOKlhE2B65vSyom7kEx2PLauq0TNm9O5Q0/MQDuUu8+oLhnMgAKpVmBHyckEyFy+Nba6vvXLIPdslVHimjeaE=,iv:CA2dSF/uyFt8znBI3qNtC4O7IhrHq/kD8c2WhB2jIdU=,tag:Ob8QC/B50gTU12XJN88PgA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
