apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nwjgLmxHiftUpf4Rka+atpS8iu1JIussa5nCcZFyFnL1QAOO/S9pT+LbiuJvUO0EaLbwI6l1BdIQfzKCpXVRXVk+ROHb/3m6p3Gof14IJX5tWYykmCE5R9IahhpDEBJfj8s4q+ZTOnr08lUV6wIRHoX+b7wY3720zus+2CGl/hvAh8WozR9eAuN/0qrf2NTgcSg9PuOOOdPPFYfuBnWnSu9luZo/1cLZINb927eint+bvudbG6Mrqb+yW4/bCY7QeZti6PqPzRNqjuF1uR6MRIBAocBu06YwCmf1+PudR6zu71qpYPS9ljCqjzBEBQY3qDFwSSW/l9OBBxRk95Sa6cbrm67G93wu6an4+gLRZKWdDPQLofIk7JJl62Y/V8eK,iv:FYipia6LzM65wXNug8hu4DfA7mBqt1w2+bMSdin4sNg=,tag:NLwm/h+je1pkUXMBZiVBrg==,type:str]
    identity.pub: ENC[AES256_GCM,data:zhpx3Rf8KUPTPy+R6d8KeQMHfzdDDBHKE/Xnjak39lelQ6nzSounR9AuFMvHYby8Z253crPco1/Una5FVOtW2cnt4Zebyx0LzVdrrjrpa4jgo488tGTZdApd38545N7jZgQGE/MmNPd7Fvl+pgYYgyZeib9QavoYwHXMwQVfIfBvhgaGUebbeczHWdToAXY+t7Tz6LpfoKJeXTnGvlwDwn227E0gRnEkOLOQhL6HD69/NrbJz2QRV1RoG5zRUJTQF20fzbqNAuUHzHXxdA==,iv:6r+sIESJO1cLMKsTv9Mkljh8cjtVl7nbyGSaMyq2fcE=,tag:HRJHQyVhvGHbhWmbIO57YA==,type:str]
    known_hosts: ENC[AES256_GCM,data:uYtBGPT1n7gAxhjzqjnXr+t8uDx/Aqk494SC0Prcym6J4TC+aHx0rqO8HZ+hnEzQB2mVd2g7jPAmtOG/eg4qh4HXAhFJt4o/sml4Ua0wbpMTpgcUg190u96lgdI3huEPWZ+33caDXfYkOv/+GVj2RD0wlGiV0j742MKTW5BTuosKungs1ZRJo2txdPJP7Rop7IM9k4X2dOQ+hwar3ZKL4/e51Gu9+2V1SmD4,iv:IgBdkJTp9zOUh62rBvsONXvpvY31q3UTCn24w5D3eWo=,tag:TVK3L0NxRLHW5lYNQfXXkg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMEZIeGJJcW1EdjZ1bCtS
            MlE2MzU5YVVjT2lwdFVWY1VndGZkSC9hQTJvClVGcDFid01paXE0NjRCWUdjNmN6
            MzdzdUd4NFhQcXV2MXM1NlVvNWdYS28KLS0tIGJKL3pOeCtGbSt4bHVZbTBSZ0Iy
            V283UGczZE05K0RMZ2lRZDQ4bk10TEEKOPGUiqwe/LsthbXAvh3PSu/P36nGL9cT
            u60+RuYboVg1g5DY3u/oX/dLkSlbKthKtiNQ4KDlIWahF6NDMj/SMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T18:30:46Z"
    mac: ENC[AES256_GCM,data:tn+gPRdiJFBJ/FegN853ju4sN2URZ7ALvO7Ca8GbgkwLYhaenzLTEneHiaK3fFrEnKRVzlWhSWnMkZ0FoJ5pTY/OyrvB8RTzUjJk3lUXLI66piczvGD7xJgTyq+X+QMBQwibRkXgFUvDnWaiy33GUr7EjuCsF+Y/ImdHM+1be7I=,iv:GG0HuRVex8qXtz7tspSAV0U/noT7XfkLqMrLgjkpMRo=,tag:HL72zDClMTnLdNJ2cJy14Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
