apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qqv7asXmRTV96Snpr85OfrFbrpC2Uy8+nhorjcbUbl+4WLOULbppuHdsfAf/vIdofahPxzx/8iDtuk3pGQ0QJsKrvLaN2FQAIsj2zrXPqlDB6V95mJLnwZ21QnOWRoS3FTD/vWYIO54cyI8feP3Th11kcfYhUvBezy9v09Qcyplk86IzJGb1NW5xZVFrrbZGBDe4vQlEHY7gXjbZOVRTSrZqGVTiDh05Bld2neZF0o/ywnocZKMj57sXeatqS78NflH5Ija9xSfOCdJgbZmfZSxOJPeg1Kkr3mziJsegWCVgJoZZ6fJ9EpL1SQEvSn2g22enZNaT7R98x5ZwPdDsFHZXIOA8SyvjC5gw0bBCM2w7j9PYUFVSzbNsyBB67dqy,iv:5wx4T8zFgbQK8PDFyjfvXC++yH5RzFSG1M/h0AEHppA=,tag:SmsaeW/2WdRC5wB4lNx8gg==,type:str]
    identity.pub: ENC[AES256_GCM,data:i6eKdHmwpDl+rFn3QAX2KnKXGRJwUHeKyA0eSM9hcdcTFOEGjQbvJJTy+zimcJJcbzbrmmPsTZjCKHDO8LWolTpRlcRI4CxePo6t4iSNnMWr1fJtr6CR4A4qfsHZTziIaYAyLZqO2yyLc0kbSV1i3LOse4aykT4B0eaiEfJJYhIesz4qXkR7ZBK6a0gJMyoGEd9kpVXkUYFlJi7I8R6EgVx+PcGhWCOcfDmL1hYdXwL/bNHgarOSQzROhGOg69K4OHjCgkR1IDCv0PRFtQ==,iv:S1xzjoB2pvvf72Z4gbsKClrnq9VbbibG16/BgBOFyZQ=,tag:k622hPIjkRRBUYVoAeEZ/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:VUDriUXWJxDfGd+dZ3TgnpdNrjw699VF/xqqvddNVaBJ97gyzSJp4fcAwGxG82jHhxnWMeNgh8Uf5UQ63XFM1huVFJptvJVgApSFFQMu2u5KBui6y/BRA+RDKaP2q39RGlQfJRD7FGxUw0Z9/TYypeQABGIBRGQk9gUaHrMRRA7OBxL5pZLcRsntWW41Ea39pJcl3o6al1Hn4h7+yCygAA3JBo183q+RBSNm,iv:xrjf2Brhzq/lgWzDZm+VrN8ZHlyoMU4cXSPYzGZ0eDM=,tag:Y4MXNLlGsFvbHSZM1JqLFw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYUVYVUtXaGozSkJXdlVo
            RjZBMFhZeWhJZzZqRzAvTlUyZVY3OHZGamdRCmZEeHlZOHdWL3Z5SGRXYk1ZS0pj
            UXllWHBUQis1ZHBpdk5aZHdIVnZSTkUKLS0tIEdpa3JmM1UrRUh4TGNrZmVBS0VE
            SDBTY1FIc2QzTWcyUEp4b05FQmpPZFEK5sppbLuZ9HYBNlcleW5PchYN3aIfy7iA
            UEt11HIhw0KYaQevcq5BBjPI0YAOA0FVihrwbGPA03K68QmkptQ+mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T22:46:41Z"
    mac: ENC[AES256_GCM,data:vrpXKldpaoEXZTuRLpiCJN7fko0svTAqIjINfb6n9aRoHS2napsZMb5sZfSdq6gxnpXfAJk8bd6HaeMfygioV7VKzHAAELe+cCTCLRZX2XrN3yoLm4Nv56JBzXwwn3Fpp0f251lsR9tNSgk+ha6vsy1fcXSs8vw0+pGPd/IbSUE=,iv:eZQcQPKHUR/e7Bcupyin+LqZBEFcbU2Fpq60dYrrL5k=,tag:LnF2Zwt2aphLAC/QpawGag==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
