apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ON8fhawtGK5OaaORE/iSJLpW7Kjiczahgn0mmXTJnU/s1s3u22a9zRN5xVJDiecOYQ7WJ2WbHvdby12p2HbSUAVeqeRJomKJoL84cip8Kwt2RymakTK5IbboioLUQ9JkAd0udmLjMCqw4fBGQrw5pyBBT0T0MMO+UVAGek6vRpXtv3wEv8TNVJES+cBuGqnQUUO/24E+dzGCpPYZBgZNXb9AADm/m2msu63TemV7Ltb0GhfOOQoZcITOEt4q/7IbqgdjVTzjqlW3rWTnPGaI5uWluJKyK2PtlWkT8FpbCUv0QSlzSGOh3bu7X8kbNR5mEW4mefdBByrf37meFUzL/witiP0X8jFXAujLk8E2SB6ubePAOt1HbM+RpDck27pB,iv:mg0K0Esz6NddVQSIXHsKU+eAdjOWeXJaJjCQu6a3ipI=,tag:k236YPgkvXAahls982tzLw==,type:str]
    identity.pub: ENC[AES256_GCM,data:fJ5dHD35yPaTID70UviYO9kRPdoe8f4UNaEPYfOGvjBeC45NzkmskH9ambkIFF/Je64k5encWwWb0DxtlWk4FnZz9Fdy7E8C6N6aoHPkx0eejudKixfK31UEokr3VBmSDnsB519GnDJYb+jSC7w+05u3+5enm2WQ8y+2DR58Vuqv98i+CE+nOdxjASD0yNUmXKyadl39omKIqqElIheQE78tq+T5bNxtCUd0hNG0hXMzvoO3AVBFPRcw3P6ibBEE/SoaB7RjNsi4XpnhXg==,iv:90yEeA1oq/da0RGviipDuPGKQHpo+e/cnwokJYQ1vQY=,tag:pGKpZmPz6XQ97tUe6oZQ+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:Oc6pA/Dp8dI4s7PWqOg+Yk55JYpcJluWltnuUVRX6Srl0YGC2rh8GPs2XQKxrFoPzWuCHbnXY5ExrLaXX/eyR7sAqb2nOOmYbN1dygwxZ92d9BDwwIKOk5BmROuCVO1rqoDWqNXSyGGi6VOyAzSjL9+3CRgYyMyRtNn++NCVpJjGqPc9OCT2VDAHGQZBcPVvm/oxbeaxYtSNCvrtzMNGt1xpEN8QcCAjPcUo,iv:TtX99v3byJQ9CtcS3DdPvuDTDYtM/Fpyq5wlG5aRSnU=,tag:X01HVKH5nLnNJO7BpR2JsA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdzIvYWxJRUxRT0tLWkRL
            a0Yxb3RVWmp2R1g2NThqaGthalFMOEZ3RW1FClRjdDFzMXlWVnczcmlST0M1TEZI
            bHJjenNQNXc5OXA3KzBLbmdaa2NCYUUKLS0tIEFob0psWEFSWXhPb2FZOTlqUjNB
            NXBBbzFRQ2MwWmNCZXNnWE9CWWVXeGsKPxAjHmWUb7FBz5A4BzdLRIx4zntPnpPd
            BpVCCGWI8KoOvWV9qISg94092YdBWq0m0DQbzCmuK9OiTU4XLqmKmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T19:59:50Z"
    mac: ENC[AES256_GCM,data:NN5kmrnS6qfGPTDPKJ2Lu/pzDSf+SQX0qc0rCtnV6fsYFEt4X5j71QL/GbH8J0curtnaxf+Dy285tVP5QEtHJq6o/b9LFi5FBrlq8bTiKVin4YTDPjtarHi3FC4/esVd/x0xKa7B9p03uIE3GntEWwhn4V3QtNCWKRYujxtNkCA=,iv:S1KZYMRpIseA5Nd3GarXLGzmnwMccPQORNdklUJAftU=,tag:7ci+NarrNzx/VoOaSPwojA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
