apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YCKnFVz//tYviIW9Iz+bSb9KfrU6W3AuO0VFrhweSe0+P9Z1cgrZei8m/NdLc1Qmmp8ArczFubf+3J+P42419mIRRgUH9q/bcGr+66D7qhwG+spkbGBetduKcr5VJ+jAFFAj40FOL3mlluoTOoZd2sxS+WTxk6OQPI4r3Gp7eBqYOEUOzHX2gdSok8Y+BRINcOIEoQYXa8n9h9z4A/3o4tfo/7X/qKz/wgQjy54IzMWqAZJRjpgupYkEzZBDQDxemwmTnW4Mire/iEriQj9VweoNSGFrjus3UZ2+pMJrmvKgsAut0SjFGbFZ5i3u3MR/q7fFtiyJJVFE6MglqIKeqmvPHEfm1KClba0ggwwBUSGFMg5DLogiWK3UsXdPxIml,iv:7Qxfm6tr8Egaj7gNhBbU/PxJkHLJbxn6ZnGMBdWnjtc=,tag:URq9uQzxmR+CEgiXKJ3V3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:6CvYdiEjCIcVNTSCa+WAUQpZNjhlu1JbEQa9yoAxQFd7k0k2q45cIA5B5BmxZqZg/x5WLBwpROJibSi94ItdZAXBcNUulNE+0ujOReOxGwBuSnN9BjiqJ7SYeYKpPuogOkhdaDp8/SVk7zegIROsZSvBWA5ibDCf+l567qoJsQd73ElgGs8weI4xZGCAS7J74xkHzShdz1mWo/dQEcqZSzS3KW7VEVMnj1H9K3pf9lRYPAvmsPJfH/h0gLmP+1SOqe7Cww4z6AUB3zfLtg==,iv:qhkW50Gann/YTCxdlNnJ73f+rB68dVkrwhPrBU1Ob3c=,tag:q/OrzTztAPEDJUDct/QweQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZXFzb7JPJ8xriv5KxwgC2aLegHZT1gEi0PqqKl3UXYBPsZn/XfAGpBXoE370Kymmv6Gkxg15TBlBkB0LBr4tFANLWpQEuc8q8uTI3Pyg1Cpbp3GDgTZTaQ3JVTjjixtDN9nttF5N0Lw80SWFPnZx7MzrNghinsKWYc6elkRenyhh7+5sHztHGEWVMIGPRuObAWgGzHIr0spypt+vneEpTcD5gjFK9ood9CgC,iv:16eyJlnMQAmky00FsBpewIgyMylaOEsfJi884ORjFlQ=,tag:1G+XRNG8/5EVf60H1Ez8Fw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnNQNzRjU3E1bUR1YU1D
            bmtLS25FRjdZNFVtUjFzVkhrVC9UYVZFcEJjCjZaMWU5YXVRZmFrWEs3eFV2OUIw
            d1JQeXV5Y3dEa0R2b2IyUkxDUTUvbjAKLS0tIFlhL2J1Q0JaU1JkcWxoK2VWVXl5
            cmw0MXNZM1hKL1ptRDFCS3JvaElST0UK3oBZsRm58R+0D2ElSY8JdYNiPEHbpz7e
            EPScfyVTSi7sjMay8jnUJd4XSbmlzfJlixMCqIaQzykYZcr2704lqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T01:45:30Z"
    mac: ENC[AES256_GCM,data:pO13hIzsaTtj6aytusujH3Pxmm18kD1frdmOHIqPzC/GpPw1T74eFBmDapJ95Pf6EWpfD5Gj+7wpPjqsvNvEo2HbvkAnoN1TBTUK3krdKicJxTQiCiOZrA91zXu6jsR/3NW5ZPruhp+p9d0exzevEewOBOjkbsbAWInNDIuYClA=,iv:YJg+hxw3vPwNQVQocktjWZv912WxTJYGMzxykf21Xkw=,tag:ZJY+BPv1gEFzlQnbkQQRvw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
