apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xyIhoPjYHhoPQU/suaob9cDNa0xqSIjqoKRk6eHF52c45Uqip8BNaqSl5xHp76hCMOn0eh1S8iBogyvs+Hd53VWsEQ2ZoT6/c7zF2rW05e08YzzD3U5qXlJGuMsVC2AXyJM0/LzkcrOpA7ImCoQn1FyDV0q3FXL78saH1aEc3i/kNj0d/MIHO8c9rCqoE33AmxoEbwDHAeezTCtaRi/jJYHQ7t9POStzWnAQ6XpvtznBUlqwkQGl/zbDsOcUErueDRDmB6of/OpcpIg+oh5pClKMDxQqUYqYfvSowgRnwrvtvPSHDP0LFnIaGzwPlC/soS+OYNGvsgLNkFtLTBMq3or+AzNca7FLJE/gn0bErURHBalx98N3DLeCOe9XsPee,iv:U8ggJ/UjltEzPWbUI2h2kJZaBIPH8pwZNvaVsleE9qU=,tag:S9NXBHqOiT9thk8cbXqmZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5TaSlfSJzjbme/mrHhjl0//OnAy2jbJkv1szYvoJ/qbvBBZ9pHjIK219dINnPs0lr7JNFPeMVxEZ1lFUnCCGdskZSZq7cRVIzXlOrAAwxKnmtTy3OtEf6dXGP4zlzMwr+lv8Hir0Aa3Lh3Vg9+y5PC45049lOz88i9/7A3ZFtqCzoyykZcsnI4HUpGyIwMlbyxzmUbCIwXOP3HEOPIdOm40qBx98aIXowHnyWpuFjH3vaHgODCm2OvxtbswYW9iJHmU6vBUrdHQLi2HVVQ==,iv:eFzMHR94tYTUccKvN1gWw/MCGkK/k+DMX2Mzmzib0bY=,tag:tACabir1DUpi9ZcV3HXWNw==,type:str]
    known_hosts: ENC[AES256_GCM,data:OAqjEyJDr9Xb7zWmbuYLQZDn22kdqipfnb6PQ+KbiDOjDM4xgO0SjPrMDNpbQ5Ca8+9jv+mN4I8zquQ1TP5VqFQkvo4foDg3f5kU0++AzpxjSScCap5FjuI/McOCGHAtEdMFW1aMIAo8AfQ6XAnvwV6lqkRx6YE3qDRgOFC7b6z/KAyDZ9pLJgkTfbUjdfA8pmXWLl/F65sC4N7TCzeeszeTjd/OVqCPxlhn,iv:0wWBYIzfWxPuHS4Vo1oSZ6hYOx8q8jqtPkPFieIbhEE=,tag:Qu2Jc59Zv7DBscYphtzu7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRHVkSGN3RnpzTVBINEpo
            YytHTzk4NjZwcXgzYi9kM2F0RmtXbHZzNGg4ClloayttR045SEJJbjljTUpMUEZj
            MHVKKzBrU2lNT3RtREF4cGZSODRMQkUKLS0tIG5saWhNbTdybDczb2JGVWJpSVJk
            VzhNeFJwQWZFWnFHV3J2NmpRWWJvajgK3cYq5B1zMwA5oNrt1NiyQtXPbCKWYddG
            NgBhkmcyQyuSM2YeVq620d2wsZGCLUQjRTolModXaglyBYm0kL9ytA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T01:36:48Z"
    mac: ENC[AES256_GCM,data:42vrZn5d9tkdcj4tnDM3D0QAfTHsUJiUxlJWCnrdHoY4+Zo/3K/uyPbphwE5ncrFa5+9EHi5dsCt2ObyuFSWkR3pK6+2oxtlfLzM1AJ+d5X3avGN1zUUgvzkGiJ4+CTOWghgAezJv5nbz8qnN3RuuqdcjrV+7evBmydYU4I1L4s=,iv:SKqFriYw1g9ujlvFzJbIfdotC1RVsaEC0LKDItKPvq8=,tag:vN1CTHWvR+QGWMmqHVpPGQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
