apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:01q91G6PRxE2xxXiVFpnuMDCQWYJtHGul/bVEAIs2x+coyCU2wvXsCu8n7YmcrO8OD1eXN0tTMPXxlOw3D1d5iv4nyYnAfPijqAjOPc1TSmayNfJKfeVlqhuaRC6QxGf+LhY8WZxdEDHcEdPvqbsoBpZekr4SW3CTA5OlXiSVBKLTEFiM9gVkJ8t6IYyMVO0zlVNf2UNbxgWGWjJTEj4H3/jkyHmAOf6CSPJx+D8+Xe3tzmm19RCB9/gcOlMK7f3bp1jPOcsiyGetBQaYeD4FLKI7vrUuL7T0IKNl4knrvgqBO2SBKUng2oR8nkC7reo3Wby8ni7jecn2L3eP1TACLuCKd0kjmmz97KBzQrJW5nVGex0nJYuEhb0PxLQN5uo,iv:vbxb5YG2ekN/Vuvy9UOGtSJFNGc+Jb5lvqYUpIA9tYI=,tag:8m3qhJMqFsND+MTgQzu30A==,type:str]
    identity.pub: ENC[AES256_GCM,data:GOo1fLLE1LOjrJerDISDD3H/2FfSAy/iWCUR1HThFCa0N8G8QfK14yAIgPoZBNQA2Pr6ReG6QRZFHoz4QeDYfdI0okgBtWR9Tw0uzrzNUEOBa7K2hNAYx6i3UY1+PxAHxUWF7xfIte6GfnAjNDLtdWar9c86qicfLq1Yc5FdN0chgV97U4zZYKM/IS0wGKGfxnactim1w9xAPeFsWYgkZVJOFVFuyoqR+KKSf3M/X6K+6luSB9eBeg2qhvvbkD7j0vxDDRP5YCKONMIA0A==,iv:lB7A0pBgg5DAD6sUio0HJsD2Klv8z75Iym7VNYR3AO4=,tag:bHvG7qYVtUr5+9D2c32Bag==,type:str]
    known_hosts: ENC[AES256_GCM,data:zJYC0/rfJSgfPH3ySfnu7S2om/bumYY36H8o4qV3iydt5TInXZmqkY/GWNgrt+c7frc1HGABoPM7t/xRE0GnO3/QVzh/G0yH7vtf+16D1QYyRJ+pEsknz9upMhw6BhRjZ9+B87D/BzMnrfpRrEtbZ2tG5nUtql2d5zNosf6ivU4IU3fpMH5x6YFDzhLDUCsvlyJYG3CYZMIHK5xNiXpS810p+bcP3mA8TiGN,iv:zH1vyuOmJkNQLzg28kcVpQ/jwNrTEEG9KSY13F97/No=,tag:1Qkq2Chzc6vkkBrt6O7gdA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxckpkcEFTZmhuR0hsWFJj
            d29Gdk9lNllXcWFHak5BSTVKaERnTE9GTWdNCmpQZUgwS1ZkVnhjZVlGRjdIYSt5
            ODY4ZllQNzQwdDZQc1I1eEdncTV6dGMKLS0tIEp3UElBdjV2cmdNWEk2UUFLcnMy
            MzhPb0szUnNyekVEVzFvSTJCdk9DeEEKBt/vQepTiP9SuI/k2nDEx4avwrF9efRR
            Gpyy4gBeAnhAtzT8owvlIfZqW/JzqaCYBUGqJE/7WYm3QlS4pQKhOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T18:33:25Z"
    mac: ENC[AES256_GCM,data:qVwv+cr5UxhaLFy83IaOPeQt8LQFpNv48+rq26czPyuWlI5wB6f20T4vh301q+9evbNoxiBnGFKaG9MP9NCf+ZHw27ebFAK5Tb2G3PzpnNhstkCJIrVYpk1Y24NJDbetrP4M0HuBN0J/GzBaoCpNLlN3HGaXJNFh+58QUFyXKKA=,iv:YAYkR9VUqYCwgzyLa7L14wKytRGbnZ2ogJ6yY/ZQsKM=,tag:UentO3yvEhk3EIbSRuDvtQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
