apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:agO6AaLevjHp0HxYc9N4qc3+N6jKzlKd/wyO6icGxbXAE5bk5oRbdpXJEOdNb1/gkwxLubEAZ9rKy6YqpCwlJ1KO4WHTIxF9CQPfdaxUXbnjZQUU801aBwgzXFLv0hTq3PDAw/Xou1SU06b4LTJtQsgJ8ToW09KEfdBPpLC1IoLZL3xyrIFI+z5uGiokZDtonGOl3fK4Wdnos/mJ0neYwvdnTEBvzbNJy80tkHNWNaWOdO4rLmn2+ANGnFfQ4eKHW+gWnBNq+cUgOXNjlUFEDvYddzRJnzfoxxJRRsFEdndFrN3OMqcwAuBp1HWHuN7JdEi4ROJDaX4GBFXgQ8AIIp9Cxdb0RUT1GKO94CEyMmtKYj/jOVSLB2k1/tm+Z8JI,iv:f9Fd2dBdFY1owt2DrZEHI1xWEwWefiG+zo0AYrsfFMY=,tag:a6cJUCP3fsjVA3M7WyI88g==,type:str]
    identity.pub: ENC[AES256_GCM,data:4Fhcz64foO5HQJ6gCjrhOEjVGzqK7Ae5J/MH0ctnRry07hPOMrIlv9heENe9nf1F2qhaEKFOL5zo0dmbbM1PMbku821wu8OZzpN7aMQnp7pHBkCDtTUXjbNe1pXTVt8VgEtesOs1TAaT9hgAhQW9UCX+qV7n0CU+J6C2Pzm59a/nrk2SoEbAgCZPaL4RLMIDs/rvg3E3zgDro9XluaAvTrwpy/Qgqp4drs6HKAhR1hcKwEnBwolG1rVfd85Zn++mZmxBIc4lSF9OHxvOjQ==,iv:LFMTgmIgzLNclYzZFuDnWGbr0Mr6DnVmjlXXM3hBMmY=,tag:5SvAO/Cs0bzvmvNPVCQzlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:XCR1NCLFIy4rOxfgRYJDs+xukLiUFV8YvaS8BtsFGISbSIxHdJCMYr0xNfLx6xctrvQY8W/xVX+OFTYc1Vi/cv47Ta7hqVtr8iZ9GFAxRF9SLFGQL0DWRzSVgcyaPxt9rS24S0WGiZy3wGYosJaUaUzJKBLuyYFPjbIRF+TKhPUh9oqLZv/LLt0ueERk5GFOjsVWvGpcNyiyRS3RCv+PotItNXGEeLNZuNWo,iv:ljCln11CXybvz+0PDOtD21FMyR2RMhpaSlmjE8+8+w4=,tag:oi51F7/XvQxoTcBrzOPGaQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTldwbDE0YWt4ZHB5YzF5
            ZDFQeTNBMHFlbyt5UkN6dGhHclNUc0hVT1hRCjdXdnozRWJ0MTRDdjdKQ2xqTlNR
            bHkrT21LcHRJN0RaRFF3TUl3OXE0WE0KLS0tIHNtZHdaV1BINmRiUTdqend3dlhV
            S2RxRnAzQitqS21IWlBydXFXK1hvWWsKq6QXWsnG7WmPm2SH9j96Na4Oq39J55wo
            5KTR/3ns9iBggwQ/FQ35Y4YPaII0XYqIlgIOVo4w1z9t+LhCHGisgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T18:46:24Z"
    mac: ENC[AES256_GCM,data:yTPth4iETJTE00g4mafGPaeZeQFUxaJvCNJk9oTtvPNdaLs1OqnEbLkB/uSWBG9YFezGpymLQQwfg+W4XK7yZRdgK2fBYZFIIKQ+kloAhIsM2JHHWwbMqaqEVRBZi+d7CxxL91eH6Uz4hOfjh4Jcn0z5u+UKjLNBDJTQp4Q2Wz0=,iv:9gyWkmTuQiycFLsMlcgaZfHfIaSo72MqCoFzHYL3k0I=,tag:mcLQ2rwK7RDllsaZgYT96w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
