apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qTUnxhSSEStKwMH+opKwihOmgrZdhFq149dvgZgCt71vepCPkV04ILC5dZ5uGz8ivJ130z8GO4n9lYnuw4hem2rclxCLruUJA166p9DouvZN0AHThfrJ8hwh/ys4YTc+0P7rXk2uSwa5qVAHtHPJe3KoZl1DQuGJ9wwtmZM5f5FakOPDwkx8YIW7DmCJgpFkwXsjn6Kr1KfgYSFHhaArXdl1N5sLXuSQR3gklDxQGDlc4WT9/oGgXJsFGyYBElwZPMyuXPTjpNuRdr4gC5wHloz6mGDxU4tpVHo2pxgpTTkgnzHsCd/8oj7jOViXPHp+B4BRvmRX1VP2uZHcg2DVbiX5ksFgxoG7sykX0J+VuNTyof1V6MuADpm/dtG+k98w,iv:/EwhPmmMhviBK7fDJqPaUxQjhPXVxwHsMErpfMzM3wU=,tag:9npReb/qK+7w/OpHAcA0XA==,type:str]
    identity.pub: ENC[AES256_GCM,data:W6IsnFP+rTIFeuBuhR4HOCB94O5uII6+WK4/033iYrCvD9/XkXDStl4CowkbvTziOh40sNdSUSEbOvGx3gOMYvJePu6dYMc5yK7u8QBqMiVNmzI2TKtVfav2TZLk7YeV0wcfPzEtcKktY8tKsrUlm3f7EmyofNVQqcNp2ivLuXGro3dd0oHrB5QAWGSD8pJh0d7vOCfVDw5Cojvz096n6+cdGAsb9zNFcOy0bK8dZpRHLQqJk32XmfqvKwGkceEzb/5AkYN9mFJftF5Wxw==,iv:6yPdwQrzz++tLHXkWQEeicw4HsrkBVOL2iqyT4aHJnU=,tag:Uii1Lr16BHyfRIKNczI7AQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VTYmhT8CWRX/LU+tStJyzPVavBKA+1UXlXdZoJJG9ryHAUGOQbCMSfH4+tKWdg+WfpNzRRnd6IbWp+PcpVFaIfCRcUdiyXHwcX+gCSPvfD6rRgdmt0bpEe0G5+ufy9kyW5RvIydL7kjzt9niRt6KYjgPiOcLl3wrMMQzM4j6gcd6702SrNkKA+B+dOC9r0/nfHAttOz8WpX7FOQnlKHsb5qkuRW/vrMVrsKD,iv:eFH4EbMK/16yq/Igrg1Cl5m2kTcXTWfOeGSj+iA7cCA=,tag:Gv+Y/XOOyk39ihpqWy4vDA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSmlFQTdhdVBIaDJhVVVQ
            ZGdVa3k0UkxrMmcyYUw4eWN0ZHp5ZFptbWlFCnJnb0M2S3FjRzhZem5uWUk3dmdw
            S2pwbUlNZ29lcTcvb2l5NVBTVW50bm8KLS0tIDJ4d29aVnhKYVVqdVAzWStjV3lP
            OFYvOGJJZ3FkZWdUaWdZY3c1V3g0QncKLP+wNA32aTvRcHi0Uo3//G4QB2+fa7Or
            8wYjoOdXE3o7yzcXbLOBs6mxrbAGCc340zzSvlMTH6bTXzh/tA+PWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-29T21:50:25Z"
    mac: ENC[AES256_GCM,data:CmzNAhnINkZXKE6mfZiaCgpci7OUmxfcnFQtFOHQCFGsvPmHI1Bh+Uo9ODE7us27kBt0QZ0lyBfopHBAv/RbAxByhb+aSbnI9q+9g60hnmODDR9ZYAV2jU/GYCw8yW6dGdcQk2BQrxcfQ1BnnW2WQhhvRDGCUxVniEUIKx+aVFc=,iv:gcbvipmHR8Cebun8cnRf1UVJsL2g79gbjLljRWs28MY=,tag:yUiffFGFPN2H9t8XTnVv+Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
