apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BKc0E+hLNX9xqwhJkyJkGZLUoqh8xsS9M1E9xIJ4MiZNXDLYjN1CWYSLDAvnfc3HnCLCuZMrnHNA+avwV/+sfWGu2hnwM49UkVDpb0nHrQtUG5JIBZ09xtHs9ejp9pls7xSUqAUbM6Rlah5u0KcOnzH6bHdyWiKC7/pvK7T/bUYcWcVQDIERa/S4mrAlu/YQJLeT6D0Hs+h2+MsgjQBFjN16/lit97TuYICDUg0FjIPvZorFGkza6A/tD62IaAwc9xkvnsWGmb7I4KgHPGlMRbO+I1g8xBkInB7YmDsxhTJewWhBiHDdPMCb2KD5P4G0S1i8f4xgiHjOkcUyvAi7cw2CoabdhZnRmzlICtihohKQqTPuHnJPX4XnPK3gAv6B,iv:tiWt5J4DGM9yvNIM5SNS0/7FaiIr30MUA/mSjgbT2fo=,tag:LAhRRa9rIxRWx5wbsR7ucQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:kDKabhpqImNPzswr6yLHoWfKoJuKz3fSPHj519tlca6oGgJ9EU+UXbadSibehRn9wB17p2S3QQvSxx0eRu/nczNreg+LNmXuFIsWJCrTbkG+ZIG8b3nFKGZQ6VOVzTet0UTO3AxdavHohHzVAT1L3TnxYcIdG4r0jAdlPW+P9mE6/sBC7SFqv7e4YOpzTdvB/TsG1eABg3+0mVEbwG3yzMtfaoeKRFmwfjzVIcXFEtuYkG8BZgfLXK0LcqFdgX7sxqut+hekcBx57oqlpw==,iv:5SSEDQyWebcTQfFK7/ZQhX9fH3q5ffKnBHEa2UOVImA=,tag:b1+t0kNyCk9l4c3IEj2Ttw==,type:str]
    known_hosts: ENC[AES256_GCM,data:OcXu0bi/ZRbb+lpNS/MErUxs/CPe2+7/Pn6XMI3z/SBH7fiMEwdDm4sISOXfXfCP7rrd/9DbTXA7Dk3n20bJTqGd+eyzKtHB30ZnznvsSDRXSoWLyaJ5mml4csu4QWJpGdYIT6M1f92TGQhE0Pt9dsHPi2Gmb+gnSpvcaISOO18zW9332c54aNiez9ZKvrT6p9O0u0sW7nzNEBdIa5kfnxPg9Cp/xjbhQdcJ,iv:EAzhKy8ZKbLCQve96laybOayTOexlBhLqGU0QK8IXjw=,tag:8d4oV2ULizQqsP5moC0ztA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM1F6bUphWm1NaVJPYU5v
            SEhTRkJtL0E0RmR5R284VXVpLzdac1h5ZFRNCm9UbWMvU0xWenpSMWZrMG9aVWJM
            TXpnQ0lMeVpQNi8xU0ZsVjJaaVIrWG8KLS0tIERaeWpKRDUvbVNFemRxL09YVG9M
            c2trR0RwdU1hUEVHV1RPbU1MK3gxancKWbzzkEdf6We6x6oYZCOjeJB5NAxt1sFR
            G8K+8W/bI3W2FNxfXpeT9VmpsZzup3ZFajm01CFjyrOENtfuGK3Hlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T08:01:17Z"
    mac: ENC[AES256_GCM,data:gFddhwQdu13bY/18jLewppYFq+y4+5PPhGEwyXqIPYolhPpaK3fm4USFrZzkOp+wyzOn1ScINvYDH4XUQpRrCywLDgDKBKMJSEg1I/cOM4aLtOiZ8HahtDRhx00pJEv/f3K5329IV21NBj+Md8U9md2nz2GIgRLNqpqWpeDjE5E=,iv:Ujt+my6ivm+yuYZcxjfSwNNaj7RBLGKfpTi0Ff2w4CA=,tag:3xmG7cgtE2VdUtdW3aW7Dw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
