apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:acBk5c0bjuXITcZZoP0RUxYVN1lEVgshjE6Rn3SA+onFToIjxFiAVTuXSoyhVpGvHDrll/Y0Ma2Ko9DzNg6SJTrPnIYxelqcECWwgMRSwJj23mGSZxDbuttIDV1QorzBN1mGKtzmnZOKYvKql+hci970HpZ8BuOrmS0Afg7rsmgIVgiOwIR9JvAgwoeu7N7CxPUibdCcWHVa5jM0vgtfvFxbTZtKUoS+Zeqn/wvEvrulFw68grDZLyr8cp0Aejvc2QjM++K/fU3VJg2jLcTHGIsNxcuQGfe6vGd7+k3DIzZDnenUgFfvs0Dvs84qz4gQGp0MEO4T8IAyl7h8QbS06N28x3dtfwDYpY3nFXecnP9CH1r7T4wxeOB8RJG0RpL8,iv:W/g1IjMX9uSNP3Je7sRD1TmSpLE1COUaqua/QXQn/l8=,tag:g1OeZ29ALvd80af6IN5Ouw==,type:str]
    identity.pub: ENC[AES256_GCM,data:SlolNW8eDXkie+GtDeDJuwyWU0t6JtRofVNRiIlQhyTtq3ORRjA7Vdsqfzm7wn2eVmvGTAp4Xwg7Pir+vJnxcQQ5Y5mgWi3i9lAx0HHUbqmDOkCOoKPx5lJSvfdbbDVJttGgd1hwqRJSylipPxt+KXm2oQf4/wgWhhk0HtOWeFJ0AATwhVX1QwPxJND4e5og8zyygsuHZ6Ymfg3i5Iozr4K9OjPIYXznWUcN6DxGvXnLiONyIOgKkUbTWblmgZc7TK7mOGSwknQjVra2gg==,iv:39K3oc9JqMlZjo8cH3f1YVXc75RvvrvQKTbZ+21AZKY=,tag:KW+pCzkewcFkCIm05H8StQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:5wKvvsNdD42JcjbNLsXE4wOX7Us8tgH14aP+VgeIb1lqFHiCjJrfY6awoeo+hyywJqg7pF7AyXiTxNnh30vMPmB62oKH1S0auvJKjvzAlvYK3fDJMYAjZeA43rKyv+JNM+gqaUUD6EqkLWwuTUuVrz0/C4maHE0l3wVJ8HKkOH+0MkttuJJRms8WDRfH+6/m0voq3rJnXxerq+dLiFLMOqx9+4N/ik9O5jVT,iv:rM9JZYDC/MeXxAv+Gp9qK4BZDQYgG6cfnGk6VlP+Pvs=,tag:I1/TY03GAzmSsyZ2hlRNaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xerwm86t75dl2v0sqq5xvzag5q6deawx5en7rqy92886049htaxqagw7yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ1RBUFNEc2M3SE00alR5
            SGEvV3d6TExTckZFKzFMR0NqYXVRR21jNG1ZClUwL0I5TGVIQ0pDU21veWxEUk1m
            bTBkcGdjSDFLNUtWWWtuQVl2SER5ZDAKLS0tIHRiajdZbjROcjViMXQ0Q1F1Vnpp
            Q0FJS2IzcGMxUzNYTXpwWkp3VGo0MGsKxs1vIcQuEHvwCDiMTJPYq4qC2UP2YIEL
            30Jw3clMFG3qJn5vPi1wxtUdy/jDTvktnN8zQvwaoTmEl5M89WVTtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T00:22:55Z"
    mac: ENC[AES256_GCM,data:1Q0s4IELvYUj9g3TpYpFDuok76GVkT0RSRWJxJ5AG4YxctixsudsMNI0zx9GClKWb/ukxU+fwcVT8pj3V/Qkeg3Nvu9DrKtJMFkDOZcPKJ8zVwrbO390EF/RosWEjWStIJXpd5WfPhx0hFQXb8dCFJp4ZIkJsCfG3FQ9AFRw8T4=,iv:bjhRxqtlvTPkMXiUM1DKpFVHAWB8Jbx8xlGq+R62yhA=,tag:qiIFBpgk+K18TlmhUJLpCA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
