---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-pass
  namespace: plex-pass
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 18.0.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      Backblaze:
        accessKey: ${BACKBLAZE_ACCESS_KEY}
        bucket: volsync-plex-pass
        name: Backblaze
        path: ""
        secretKey: ${BACKBLAZE_SECRET_KEY}
        type: s3
        url: https://s3.us-west-000.backblazeb2.com
    plex:
      # User Defined
      serverIP: ${PLEX_IP}
      disableGDM: true
      requireHTTPS: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - plex.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: plex.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/default/media
        mountPath: /media
        server: ${NFS_SERVER}
      config:
        enabled: true
        mountPath: /config
        readOnly: false
        storageClass: ""
        volsync:
          - credentials: Backblaze
            dest:
             enabled: true
            name: plex-pass-volsync-config
            src:
              enabled: true
            type: restic
      transcode:
        enabled: true
        medium: Memory
        mountPath: /transcode
        targetSelectAll: true
        type: emptyDir