apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: intel-device-plugins-operator
    namespace: intel-device-plugins-operator
spec:
    interval: 5m
    chart:
        spec:

            chart: intel-device-plugins-operator
            version: 25.0.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values: